lib/azure/armrest/virtual_machine_manager.rb

Use this in conjunction with creating a new VM for validation purposes.

Added valid vm size constant for use with creating vm's.

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_manager.rb
lib/azure/armrest/event_manager.rb
lib/azure/armrest/virtual_machine_manager.rb

Rough draft which make REST API calls to the Azure Resource Manager API to gather events for subscriptions, resources and resource groups.
Also added a parent class and added inheritance to the virtual machine manager class.

ARM Event Manager

---

Rakefile
lib/azure/armrest.rb
lib/azure/armrest/virtual_machine_manager.rb
spec/virtual_machine_manager_spec.rb

This adds an initial set of tests for VirtualMachineManager and fixes a require.

Added tests, fixed a require

---

lib/azure/armrest.rb
lib/azure/armrest/storage_account_manager.rb

This is just my initial pass at a StorageAccountManager class.

Add StorageAccountManager class

---

lib/azure/armrest/virtual_network_manager.rb

Initial code for a VirtualNetworkManager class.

Add VirtualNetworkManager class

---

lib/azure/armrest/subnet_manager.rb

Initial code for a SubnetManager class. This is a subclass of VirtualNetworkManager.

Add SubnetManager class

---

lib/azure/armrest.rb
spec/virtual_network_manager_spec.rb

An initial set of specs for the VirtualNetworkManager class.

Specs for VirtualNetworkManager

---

lib/azure/armrest/storage_account_manager.rb
spec/storage_account_manager_spec.rb

This is the initial test suite for the StorageAccountManager class.

Add StorageAccountManager specs

---

lib/azure/armrest.rb
lib/azure/armrest/availability_set_manager.rb
spec/availability_set_manager_spec.rb

This is the initial set of specs for the AvailabilitySetManager class. I also modified the methods not to modify the @uri instance variable.

AvailabilitySetManager initial specs

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_manager.rb

This modifies the constructor so that it accepts an options hash and gets the initial bearer token.

Constructor modifications

---

.travis.yml

We probably want to allow builds to fail on ruby-head and jruby-head.

---

lib/azure/armrest/virtual_machine_manager.rb

This threads the list and list_all methods so that multiple requests are made concurrently rather than sequentially.
We will eventually want to do this for any method that makes multiple requests, but I just want to start with these for now.

Add thread support for list and list_all in VirtualMachineManager

---

lib/azure/armrest/storage_account_manager.rb

This PR udpates the get and list methods so they actually work, and I added some private helper functions.

Updates to the StorageAccountManager

---

README.md
Rakefile
azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/armrest_manager.rb
lib/azure/armrest/availability_set_manager.rb
lib/azure/armrest/event_manager.rb
lib/azure/armrest/storage_account_manager.rb
lib/azure/armrest/subnet_manager.rb
lib/azure/armrest/version.rb
lib/azure/armrest/virtual_machine_extension_manager.rb
lib/azure/armrest/virtual_machine_manager.rb
lib/azure/armrest/virtual_network_manager.rb
spec/armrest_manager_spec.rb
spec/armrest_module_spec.rb
spec/availability_set_manager_spec.rb
spec/storage_account_manager_spec.rb
spec/subnet_manager_spec.rb
spec/virtual_machine_extension_manager_spec.rb
spec/virtual_machine_manager_spec.rb
spec/virtual_network_manager_spec.rb

I finally got annoyed enough to make this change. Multiple commits caused by annoying differences between Linux and OSX shell commands.

Armrest vs ArmRest

---

lib/azure/armrest/armrest_manager.rb

This updates the ArmrestManager.configure method to set a default subscription if one isn't explicitly specified and raises an error if no associated subscriptions are found. I also added some documentation.

Set default subscription in ArmrestManager.configure method

---

azure-armrest.gemspec
spec/availability_set_manager_spec.rb
spec/storage_account_manager_spec.rb
spec/subnet_manager_spec.rb
spec/virtual_machine_extension_manager_spec.rb
spec/virtual_machine_manager_spec.rb
spec/virtual_network_manager_spec.rb

rspec 3 has been out for over a year. I think it's time to get on the bandwagon.

Update to rspec 3

---

lib/azure/armrest/virtual_machine_manager.rb

When we gather information about virtual machines using the *get_vms* method it does not contain public and private IP addresses, which were there in the ClassicCompute namespace.
Instead, we are given a URI which will provide the following IP address information in a RESTful GET:
- private IP Address details
-  another URI to the public IP Address
This PR gathers the IP configuration information described above and inserts it into the VM hash returned by the get_vms/list method.

Populate VM hash with IP configurations from Compute.Network namespace.

---

lib/azure/armrest/availability_set_manager.rb

This modifies the list method so that it returns availability sets from all resource groups if no resource group is specified.

Modify list method

---

lib/azure/armrest/virtual_machine_manager.rb

Grabs the power status value from the VM instance view and inserts it into the VM hash.

Get VM power status value 

---

lib/azure/armrest/virtual_machine_service.rb
spec/virtual_machine_service_spec.rb

This marks a few of our internal methods as private, and updates the capture method.

Mark some internal methods as private, update capture method

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

This PR replaces the old code for storage accounts which was basically alpha code that doesn't actually work. This updates the code to incorporate Bill's refactor, and actually works.

Storage account revamp

---

lib/azure/armrest/storage_account_service.rb

This passes the resource group as a thread local variable and generates the url inside the thread.

Fixed thread issue in list method.

---

lib/azure/armrest/resource_service.rb

This updates/fixes the list method, as it needs to use the internal configuration object and instance variable rather than old instance methods.

Fix bug in Resource#list method

---

CHANGES
azure-armrest.gemspec
lib/azure/armrest/version.rb

Update the CHANGES file, the version.rb file, and some minor gemspec formatting.

Prep for release 0.0.2.

---

lib/azure/armrest/version.rb

Last release before the json refactor gets incorporated.

Update version to 0.0.3.

---

lib/azure/armrest.rb
lib/azure/armrest/availability_set_service.rb
lib/azure/armrest/network/ip_address_service.rb
lib/azure/armrest/network/network_interface_service.rb
lib/azure/armrest/network/network_security_group_service.rb
lib/azure/armrest/network/subnet_service.rb
lib/azure/armrest/network/virtual_network_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
lib/azure/armrest/template_deployment_service.rb
spec/storage_account_service_spec.rb
spec/template_deployment_service_spec.rb

This left some classes untouched. Most importantly `VirtualMachineService` is subject to the same refactoring after some discussion.

Simplify implementation with ResourceGroupBasedService base class

---

CHANGES
lib/azure/armrest/version.rb

I've updated the changes for 0.0.4 and bumped the version. Once merged I'll do a release.
Please let me know if there's anything you want added to the CHANGES file.

Gem prep for 0.0.4

---

lib/azure/armrest/resource_provider_service.rb

Avoid marshaling anonymous class

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

This adds the blob_properties method for getting information on a single blob, and the delete_blob method for deleting blobs. I also altered a few methods so that any options are always the last argument.
Among the information the blob_properties method returns is x_ms_copy_source, which could be used to get OS info.

Add the blob_properties method.

---

lib/azure/armrest/virtual_machine_service.rb

This fixes the series method so that it users lowercase, in line with the changes from PR #116.

Fix case in series method.

---

lib/azure/armrest/armrest_service.rb

Upon further review, it seems better to emit a warning, rather than raise an error, if a disabled subscription is found. You can still perform read operations, even with a disabled subscription.

Only raise a warning if subscription is not enabled.

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

Hello all !
I'm using azure-armrest and I wanted to upgrade it to manage blob snapshots.
Can you please take a look at my PR and tell me if I'm doing it wrong. I'll fix it asap.
Thanks !

Blob's snapshots

---

lib/azure/armrest/model/base_model.rb

The auto-created nested model class used to be anonymous. Now it is named after the attribute name, preserving the path. For example, 
```
irb(main):010:0> v.properties.storage_profile.os_disk.class
Azure::Armrest::VirtualMachineModel::Properties::StorageProfile::OsDisk < Azure::Armrest::BaseModel
``` 
This work was inspired by https://github.com/ManageIQ/azure-armrest/pull/137

Nested model class now is named after the attribute name

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/models/storage_account_spec.rb
spec/storage_account_service_spec.rb

Added StorageAccount#get_blob and support methods,
required to support SmartStat analysis for Azure.

Added storage methods required for SmartState.

---

lib/azure/armrest/model/storage_account.rb

Documentation update that more fully explains the options.

Updated documentation for the get_blob_raw method.

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/virtual_machine_image_service.rb
spec/virtual_machine_image_service_spec.rb

Addresses https://github.com/ManageIQ/azure-armrest/issues/142

Updated VirtualMachineImageService class 

---

lib/azure/armrest/storage_account_service.rb

It turns out that the response for a StorageAccountService#create call is empty if the resource does not already exist. The result is an error described in https://github.com/ManageIQ/azure-armrest/issues/156.
This modifies the create method so that it calls get afterwards if the returned value is nil.
I also removed the default hash value for the last parameter. It is now a mandatory argument.

Modify the StorageAccountService#create method

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb
spec/armrest_service_spec.rb

This adds some basic logging support. It's really just a wrapper for RestClient.log=.
There are also some misc. documentation updates.

Add logging support.

---

lib/azure/armrest/model/storage_account.rb

Forgot some internal methods used in the StorageAccount model that needed to be updated for 0.3.x.

Fix private rest method calls in StorageAccount model.

---

lib/azure/armrest.rb
lib/azure/armrest/billing/usage_service.rb
lib/azure/armrest/model/base_model.rb
spec/usage_service_spec.rb

This PR adds a UsageService class that people (including us) can potentially use to track resource consumption.
https://msdn.microsoft.com/en-us/library/azure/mt219001

Add UsageService class, specs, and related changes.

---

lib/azure/armrest/armrest_service.rb

Encode url before handing to RestClient to execute a request

---

azure-armrest.gemspec

Updating gem dependencies to see if we can eliminate Hakiri warnings.

Update gem dependencies to most recent versions.

---

lib/azure/armrest/model/storage_account.rb

The current code for StorageAccount#blobs has two problems.
The first one is that it doesn't support all of the possible options that are available. The third argument allows for the addition of snapshots, but that's it. There are many more possible options users should be able to choose them - prefix, delimiter, timeout, include, maxresults and marker. Furthermore, in addition to snapshots, there are also metadata, uncommittedblobs and copy blob options that users can select as part of the `:include` option.
Secondly, it turns out that in some cases (3 out of 104 cases in local testing), the code requires multiple calls to get the blob information. The first call returns only partial information and sets a `NextMarker` element token. We must then make a second call with this token as …

Fix and refactor the StorageAccount#blobs method.

---

lib/azure/armrest/model/storage_account.rb

This modifies the `StorageAccount#blob_delete` method to return a ResponseHeaders object. I also modified the `copy_blob` method to return the object created instead of just the headers (though the headers are included as part of the object).
There are a couple other minor tweaks, like using `concat` instead of "<<" + "flatten".

Update the delete_blob method to return a ResponseHeaders object

---

.travis.yml
Gemfile
azure-armrest.gemspec
spec/spec_helper.rb

Fixes this issue https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions
- Added simplecov to spec helper
- Also added after script test to run codeclimate reporter

Updated Codeclimate gem

---

lib/azure/armrest.rb
lib/azure/armrest/configuration.rb
spec/armrest_module_spec.rb
spec/configuration_spec.rb

Minor update to last PR, this sets the authority_url and resource_url before calling fetch_token if the user calls environment= explicitly.

Update environment= accessor to udpate auth and resource urls.

---

lib/azure/armrest/armrest_service.rb

Last refactoring #243 introduced a bug, where `while` loop should be `until` loop.
There is a case for `poll` method that needs special attention. The poll may return an empty body that cannot be resolved into a status.
This PR addressed both issues.

Fix poll and wait methods

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb

This is an attempt to deal with Timeout errors that occasionally occur when calling `StorageAccount#list_all_private_images`. Specifically, it deals with timeouts (or ECONNREFUSED) in the call to `StorageAccount#blob_properties`.
https://github.com/ManageIQ/azure-armrest/issues/275 (second issue)
It catches the error, sleeps for 1 second, then retries. Up to a maximum of 3 attempts. If it still fails, it issues a warning and moves on instead of failing completely.

Deal with failure when calling blob_properties inside get_private_images

---

lib/azure/armrest.rb
lib/azure/armrest/container_service.rb
lib/azure/armrest/model/base_model.rb
spec/container_service_spec.rb

This PR adds the `ContainerService` class. It's a straightforward `ResourceGroupBasedService`.

Add ContainerService

---

lib/azure/armrest/storage/image_service.rb

Doc fix for ImageService

---

lib/azure/armrest/model/storage_account.rb

Seems I forgot an assignment operator.

Fix message bug

---

lib/azure/armrest/storage_account_service.rb

This updates the `get_private_images` method (used by the `list_all_private_images` method) so that it filters out "diagnostic" containers before attempting to get blob information. These are containers that are automatically generated for VM's using unmanaged storage that turn on diagnostic information. They don't - or at least they shouldn't - store private images.
In practice this meant dispensing with the `all_blobs` method and handling the containers internally.
The net result was a slight increase in speed (since we're making fewer http requests), and about a 25 percent reduction in memory in informal testing (from 600mb to about 450mb). I cannot give a more precise amount since the amount of memory reduction will depend on just how many diagnostic containers a subscription has.

Filter out diagnostic containers in get_private_images

---

azure-armrest.gemspec

Bump nokogiri to at least 1.8.1 to avoid security warnings

---

.travis.yml

- Add [sudo:false](https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments) and [cache:bundler](https://docs.travis-ci.com/user/caching/#Bundler) for faster Travis runs. 
- Bump tested Rubies to the latest.

Fasterer travis

---

CHANGES
lib/azure/armrest/version.rb

Added changes for 0.9.0 and bumped version.

---

lib/azure/armrest/armrest_service.rb

Ensure min and max values for sleep.

[FINE] Ensure value passed to sleep method is an integer.

---

lib/azure/armrest/resource_group_based_service.rb

When the `build_id_string` method was refactored, I accidentally introduced a bug in the `TemplateDeploymentService#delete_associated_resources` method. That method uses a combination of `build_id_string` and `delete_by_id`. The problem is that both methods append an `api-version` string, resulting in an invalid URL.
This PR modifies the `get_by_id` and `delete_by_id` methods so that the api-version string is only appended if it's not already present.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1497175

Don't append api-version string if already included

---

lib/azure/armrest/virtual_machine_service.rb

The `VirtualMachineService#delete_associated_resources` method currently doesn't handle VM's backed by managed disks properly, and will fail when it tries.
In addition, I noticed we weren't handling the possibility of a VM without a public IP, so I handle that possibility as well.

Handle managed disks and private IPs when deleting associated resources

---

lib/azure/armrest/network/route_service.rb
lib/azure/armrest/network/route_table_service.rb

Minor fixes for the Route and RouteTable services.

Doc updates for Route service classes

---

lib/azure/armrest/virtual_machine_image_service.rb
spec/virtual_machine_image_service_spec.rb

This adds the `VirtualMachineImageService#get` method, and also does some internal refactoring to avoid repetitive code.

Added get method, plus some internal refactoring

---

lib/azure/armrest/virtual_machine_service.rb

Currently the `VirtualMachineService#delete_associated_resources` method can delete the OS disk, but it cannot delete attached disks (i.e. data disks). This PR adds a `data_disks` option, which is false by default. If true it will iterate over all attached data disks and delete them.
Needed for https://bugzilla.redhat.com/show_bug.cgi?id=1788053
For testing, I created three VM's in the Azure dev environment, one with no attached disks, one with 1 attached disk and one with 2 attached disks. All 3 were deleted successfully.

Support data disk deletion when deleting associated resources

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml
azure-armrest.gemspec

Depends on: https://github.com/ManageIQ/miq_bot/pull/506

Use manageiq style

---

lib/azure/armrest/armrest_service.rb

If an Azure REST API call returns an error response with a content-type of application/xml then trying to JSON.parse() or err.try(:message) is leading to invalid exception message strings being returned.
Fixes https://github.com/ManageIQ/azure-armrest/issues/405

Handle application/xml exception content-types

---

azure-armrest.gemspec

https://github.com/advisories/GHSA-jxhc-q857-3j6g

Update the addressable gem to ~> 2.8

---

azure-armrest.gemspec

Fixes https://github.com/ManageIQ/azure-armrest/issues/421

Update parallel to current version
