ManageIQ/azure-armrest

lib/azure/armrest.rb
lib/azure/armrest/virtual_machine_manager.rb

Since all classes will probably use this, I've moved it into the main module.

Move COMMON_URI to Azure::ArmRest module

---

lib/azure/armrest/armrest_manager.rb

This just adds an internal method for auto-appending the api-version, and joining URL pieces a little more cleanly.

Cleanup api-version appending

---

lib/azure/armrest/armrest_manager.rb
lib/azure/armrest/virtual_machine_manager.rb

This PR revamps the VirtualMachineManager. It updates the list method and adds the list_all method, which will give us all information for all subscription + resource group combinations.
It also no longer assumes a resource group or subscription id is set (and previously it would bomb if they weren't set) so the @base_url instance had to be removed. These must still be optional, so instead I've added a build_url method that instance methods can use to construct url's prior to making requests, and a set_default_subscription private method that will use the first subscription found if not already set.
Lastly, we have to deal with some api_version wonkiness on Microsoft's end, where certain methods currently only work with older api version strings.
Here are some examples:
vmm = …

VirtualMachineManager updates

---

lib/azure/armrest/virtual_machine_manager.rb

This also gets rid of the properties shortcut.
First, I realized we needed some information that shortcutting to the 'properties' attribute removed. We need that back
Second, I got irritated with the response returning an array of one element instead of just returning one element. As far as I can tell, a VM cannot have more than one set of properties at the same time. The API docs show it returning a single hash as well, not an array, so I'm not sure why it does that. This could be an api-version issue, but I'm not sure.
Anyway, for now we go with returning a single value per resource rather than one-element arrays, which was getting painful to unravel.

Return a single element rather than a one-element array.

---

lib/azure/armrest/virtual_machine_manager.rb

This addresses a bug I introduced when I switched to just retrieving a single element.

Fix for list and list_all methods.

---

lib/azure/armrest/armrest_manager.rb
spec/armrest_manager_spec.rb

This PR adds the provider_info, resources, tags and tenants instance methods. I also added some more basic specs.

Add provider, resource, tag and tenant methods

---

lib/azure/armrest/armrest_manager.rb

This adds an accept option, and sets the Accept header in all of our private http request methods. This ensures we actually get back the content type we're expecting.

Add accept option, set accept header

---

lib/azure/armrest/armrest_manager.rb
spec/armrest_manager_spec.rb

This adds two new methods, locations and publishers. The locations method returns just a plain array of locations, either on a per-provider basis or the locations for all providers. The publishers method returns a list of publishers (in the form of JSON objects), which can be narrowed by provider and region.

Add locations and publishers methods

---

lib/azure/armrest/virtual_machine_manager.rb

This adds two new methods to the VirtualMachineManager class, series and offers. The offers method returns a list of available VM's from a provider within a specific region.
The series method returns an array of VM series (aka sizes or flavors) available for a given location and optional provider (the default is Microsoft.Compute). These correspond to the MS pricing units you can find here:
http://azure.microsoft.com/en-us/pricing/details/virtual-machines/
So, a single entry would look like this:
```{"name"=>"Basic_A0", "numberOfCores"=>1, "osDiskSizeInMB"=>1047552, "resourceDiskSizeInMB"=>20480, "memoryInMB"=>768, "maxDataDiskCount"=>1}```å

Add series and offers method

---

lib/azure/armrest/armrest_manager.rb

Setting a subscription_id within methods was more important before we didn't set a default in the configure method. But now that we do that, specifying a subscription_id for each and every method simply isn't necessary, and it was becoming cumbersome to support it.
In practice I suspect most people will only be dealing with a single subscription. I know we are. And there's a subscription_id accessor that users can set if needed.

Dispense with subscription_id arguments in methods

---

lib/azure/armrest.rb
lib/azure/armrest/virtual_machine_manager.rb

First and most importantly, this fixes a bug in the list method caused by my initial threading implementation. The fix does require the thread library (in the Ruby stdlib), but that's minor, and we'll probably need it elsewhere. Also, rather than grab just the first result, we want to flatten all results. These bugs were discovered by bzwei.
Second, it removes the subscription_id argument for a couple of methods. This is in line with the philosophy of letting users set that as needed, rather than having on deal with it in every method.

Fix list method, remove subscription_id arguments

---

lib/azure/armrest/armrest_manager.rb
lib/azure/armrest/virtual_machine_manager.rb
spec/armrest_module_spec.rb
spec/virtual_machine_manager_spec.rb

The primary change in the PR is that the private methods that build URL strings now accept a local api-version string as the first argument. The problem with setting the api_version instance variable directly is that subsequent method calls could fail if the version wasn't sufficient for that particular method. Still a nuisance, but at least it doesn't break code.
Another change here is the ability to set a provider in the constructor, which lets users set 'Microsoft.Compute' or 'Microsoft.ClassicCompute'. It will use ClassicCompute by default, but at least it's configurable now, whereas it was hardcoded to Classic before.
There was also a minor change where I removed the VALID_VM_SIZES constant, since we can get that information from the series method now.

Better api-version handling and other tweaks

---

lib/azure/armrest/armrest_manager.rb
lib/azure/armrest/virtual_machine_manager.rb
spec/virtual_machine_manager_spec.rb

This PR implements working versions of the start, stop, restart, deallocate, delete and generalize methods.
These are asynchronous methods, so they do not wait for the status to fully change, but the "return!" method you see in the source will raise an error if the initial op call fails.
At the moment it's up to users to check the status of the VM's. In a separate PR I will add a status method that easily lets users get the status of the VM they just changed the power state of, but I want to think about how it should be implemented for a bit.

Implement power operations

---

lib/azure/armrest/virtual_machine_manager.rb

This PR fixes the vmm.get method which was broke, and adds two wrapper methods for convenience - get_model_view and get_instance_view.

Fix the get method, add some handy methods

---

lib/azure/armrest/availability_set_manager.rb
spec/availability_set_manager_spec.rb

This PR refactors the AvailabilitySetManager to use the latest API changes since this was first implemented. A few specs were removed that no longer applied as well.

Refactored AvailabilitySetManager

---

lib/azure/armrest/armrest_manager.rb

It turns out there's a PATCH request for HTTP and the Azure REST API uses it for certain things, like updating resource group tags.
This just adds a handy wrapper method for it around restclient to match our other wrappers.

Added wrapper for PATCH http requests.

---

lib/azure/armrest/virtual_machine_manager.rb

The REST API for Azure doesn't provide resource group information for a VM. Since we're explicitly iterating over each group in the list method, we can insert it ourselves into the hash.
It's handy to have, and we need this information for various operations within ManageIQ.

Add resourceGroup hash key

---

lib/azure/armrest/virtual_machine_manager.rb

This addresses https://github.com/ManageIQ/azure-armrest/issues/44 (failure when getting classic compute info).

Skip network information gathering for anything but Microsoft.Compute.

---

spec/armrest_service_spec.rb
spec/spec_helper.rb

This moves the providers class variable into the individual spec so we can dispense with rspec warnings about accessing class variables.

Fix spec warning

---

azure-armrest.gemspec
lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb
spec/spec_helper.rb

This new design validate whether a cached token has expired. Once expired a new token is retrieved and re-cached. 
An actual test shows Azure token expires in one hour after the first API call to use the token, not one hour after the token is generated. Therefore the expiration date is calculated locally, not the moment to call `configure`, but at the first call to method `token`, because most likely the value is used immediately to make API calls.
A new spec test is added to test this feature.

New design to cache tokens that considers expiration

---

azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/resource_service.rb
spec/resource_group_service_spec.rb
spec/resource_provider_spec.rb
spec/resource_service_spec.rb

This adds separate classes for resources, resource groups and resource providers.
Supersedes https://github.com/ManageIQ/azure-armrest/pull/50

Add Resource service classes and specs

---

lib/azure/armrest/armrest_service.rb
spec/spec_helper.rb

Now the key in the hash is lower case.
Plus some minor refactoring.
Rename `@@providers` to `@@providers_hash` to avoid some naming confusion because the class has anther `providers` method.

fixed #70: provider name is now case insensitive

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/virtual_machine_service.rb
spec/armrest_service_spec.rb

The previous renaming in #72 did not complete all the occurrences which causes build failure.

fix completed renaming from @@providers to @@providers_hash

---

lib/azure/armrest/virtual_machine_service.rb
spec/virtual_machine_service_spec.rb

This fixes and updates some things in the VirtualMachineService class.
* Fixes the provider= method. This is currently broke.
* The add_network_profile and add_power_status methods blow up when a specific resource group is provided, so they are now only called if no resource group is provided. More on that below.
* We never really went back and updated the way the default resource groups were being set after Bill's configuration PR. This addresses that.
* I commented out the create and update methods, since they aren't actually implemented yet.
* The code now explicitly raises an error in most methods if a resource group is not provided.
* I refactored the list method slightly, only creating a mutex if there's a result. This matches what we do in the other service class list methods.
* I …

Fix list and provider= methods, and other tweaks

---

lib/azure/armrest/template_deployment_service.rb
spec/template_deployment_service_spec.rb

To be consistent with other services, two methods are renamed
`list` => `list_names`, a short version that returns deployment names only 
`list_with_details` => `list`, a full version that returns bulk information for all deployments.

Rename list and list_with_details

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

It seems the storage account api is in a bit of flux at the moment, as the api version that we gather dynamically is not actually supported. For now we have to set it to '2015-05-01-preview' as per the docs to get things to work.
I suspect this is tied to a change in the results that are returned by the list_account_keys method. Previously this method returned the keys plus the account info. It seems that now it only returns the key info.
So, I've updated the "get" method to accept an optional 3rd argument that will automatically gather the key information as part of the output if desired. I'm pretty sure we're going to need these keys to get at the metrics table info.
I also added a "list_subscription" method.

Update get method, fix api-version

---

lib/azure/armrest/virtual_machine_service.rb

This fixes two issues with the capture method. First, :destinationContainer should be :destinationContainerName, and second, the vmname was missing from the url.

Fix bugs in capture method.

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

This replaces https://github.com/ManageIQ/azure-armrest/pull/21
With JSON wrapper classes we can get real classes back instead of plain hashes, and add custom methods to them as we see fit.
This PR does not modify the service classes. They still return hashes for now, but you can still use these wrapper classes by calling .to_json first. Basically, I wanted this first step reviewed before altering other code.
Some sample code:
vmm = Azure::Armrest::VirtualMachineService.new(conf)
json = vmm.get('miqazure-win2k8', 'miqazure-dan1', true).to_json
vm = Azure::Armrest::VirtualMachine.new(json)
p vm.properties.hardware_profile.vm_size # => "Standard_A1"
p vm.properties.storage_profile.os_disk.os_type # => "Windows"
p vm.properties.os_profile.computer_name # => "miqazure-win2k8"

Implement JSON base wrapper classes

---

lib/azure/armrest.rb
lib/azure/armrest/network/ip_address_service.rb
lib/azure/armrest/network/network_interface_service.rb
lib/azure/armrest/network/network_security_group_service.rb
spec/ip_address_spec.rb
spec/network_interface_service_spec.rb
spec/network_security_group_spec.rb

This is an initial implementation of a wrapper class for gathering NetworkSecurityGroup info. I haven't added create or delete methods yet, but figured we probably won't need that for some time.

Add a NetworkSecurityGroupService class.

---

lib/azure/armrest/virtual_machine_image_service.rb

Should be "@api_version" (missing '@' symbol) in build_url method.

Fix bug in build_url method.

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

This adds a custom resource_group, tags and inspect method to the BaseModel wrapper class.
The resource_group parses the group name from the id field.
The tags method was necessary in order to avoid getting back an OpenStruct. For that particular attribute we want a literal hash.
The inspect method shows nicer output, including the current class name, instead of a vanilla OpenStruct.
I also added some specs.

Add custom resource_group, tags and inspect methods to BaseModel

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/availability_set_service.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/network/ip_address_service.rb
lib/azure/armrest/network/network_interface_service.rb
lib/azure/armrest/network/network_security_group_service.rb
lib/azure/armrest/network/subnet_service.rb
lib/azure/armrest/network/virtual_network_service.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/resource_service.rb
lib/azure/armrest/storage_account_service.rb
lib/azure/armrest/template_deployment_service.rb
lib/azure/armrest/virtual_machine_service.rb
spec/ip_address_spec.rb
spec/network_interface_service_spec.rb
spec/network_security_group_spec.rb
spec/storage_account_service_spec.rb
spec/template_deployment_service_spec.rb
spec/virtual_network_service_spec.rb

This PR alters the get/list/list_all methods to return our JSON wrapper classes.
It also removes the threaded code, since the API allows us to get all resources for a given subscription. Please update any +list+ calls with +list_all+ if you want all information.

Refactor get and list methods to return JSON wrapper objects

---

lib/azure/armrest/virtual_machine_extension_service.rb
spec/virtual_machine_extension_service_spec.rb

This revamps the VirtualMachineExtensionService class so that it actually (mostly) works, as the previous code was basically alpha code.
There is a known issue with the list method, and for now it doesn't work because it's not supported by the MS SDK at the moment.  See also https://github.com/Azure/azure-xplat-cli/issues/1826.
Generally speaking we can get extension information out of the VirtualMachineService class methods, but I thought we should at least get this to a better state.

Revamped VirtualMachineExtensionService

---

lib/azure/armrest/network/subnet_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
lib/azure/armrest/template_deployment_service.rb
lib/azure/armrest/virtual_machine_service.rb
spec/storage_account_service_spec.rb
spec/template_deployment_service_spec.rb

This is a continuation of #88 
Mainly `VirtualMachineService` and `StorageAccountService` are refactored based on `ResourceGroupBasedService`.
It follows the guideline http://talk.manageiq.org/t/armrest-gem-guideline/973

Simplify implementation with ResourceGroupBasedService base class(2)

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

With this work all attributes are by default objects instantiated from a subclass of the `BaseModel` unless they are declared to be remain a `Hash`.
The declare is through `attr_hash` which accepts direct attributes in string or symbol or nested attributes in string only format.
All camel_case methods automatically converted by openstruct are removed.
From the user experience point of view, no openstruct object is exposed.

Refactor to encapuslate all attributes to be BaseModel or Hash based

---

CHANGES
azure-armrest.gemspec
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/models/storage_account_spec.rb

This PR defines a custom StorageAccount json wrapper class. This class defines its own methods for getting blob and container information. With this class you can now do something like:
sas = Azure::Armrest::StorageAccountService.new(conf)
sa = sas.get('miqazuredan17573', 'miqazure-dan1', true)
sa.containers.each{ |container| p container.name }
sa.blobs('vhds').each{ |blob| p blob }
Internally it defines different subclasses such as Container, Blob, BlobServiceProperty, etc.
I've also added some basic specs.

Add custom StorageAccount class with its own methods

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/network/ip_address_service.rb
lib/azure/armrest/virtual_machine_service.rb
spec/armrest_service_config_spec.rb

This adds a VirtualMachineSize wrapper model, and updates the VirtualMachineService#series method to utilize it instead of returning a plain hash.
I also removed the old VirtualMachineService#create code and comments since it's now handled by the superclass.
It also updates the rspec syntax in a few places to eliminate warnings.

Add a VirtualMachineSize model

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb

1. Avoid the method naming conflict for `namespace` introduced by gem `more_core_extension` if it is required in the application
2. Treat `properties/outputs` as a hash in `TemplateDeployment`

Provider namespace

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_service.rb

The all_blobs method needs to explicitly pass the key to the containers method.
I also added the :container attribute to the Blob object. This will help comparing blob image names with VM images.

Fix all_blobs method

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

This PR adds the container_properties and container_acl methods to the StorageAccount class. It also sets a :private? attribute when the container_acl method is called.
These could be used to determine which images to make available for provisioning.

Add container_properties and container_acl methods

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

This PR adds the copy blob method. We'll need this for ManageIQ to copy stuff out of "system" (or other deeply nested hierarchies) for provisioning.

Added copy_blob method

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

This PR adds the list_all_private images that lets users easily retrieve a list of .vhd uri's that are available for provisioning.

Add a list_all_private_images method

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/models/base_model_spec.rb

This modifies the list_private_images method to return an PrivateImage object, which is an amalgam of the BlobProperty and StorageAccount objects. With this change you can do something like this:
```
sas.list_private_images('miqazure-dan1').each do |image|
puts image.storage_account.name # storage account name, e.g. "miqazuredan12006"
puts image.storage_account.properties.primary_endpoints.blob # "https://miqazuredan12006.blob.core.windows.net/"
puts image.x_ms_meta_microsoftazurecompute_ostype
end
```
I've also added a .to_h method to the BaseModel class that returns the original hash passed to the constructor, and use it for the list_private_images method.

Modify the list_private_images method to return a PrivateImage object

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb

This modifies the list_private_images method so that the "main" object is a Blob, and .blob_properties method gives you blob property information if you need to get at that directly. The .storage_account method is still there as well, if needed.
I also added two methods for convenience - :uri and :operating_system.
There was one minor fix required for the StorageAccount class as well.

Modify the list_private_images method to include more information

---

lib/azure/armrest/resource_provider_service.rb
spec/resource_provider_spec.rb

This is the first part of an overall refactoring where I try to eliminate the providers_hash class variable and use our ResourceProviderService instead.
This PR adds a list_all method. Unlike the list method, this includes providers that may not be available to the current subscription.

Add a list_all method to ResourceProviderService

---

lib/azure/armrest.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/network/network_security_rule_service.rb
spec/network_security_rule_spec.rb

This adds a NetworkSecurityRuleService class. This class will likely be part of the MIQ effort to gather security group information.
Some basic specs are included, too.

Add a NetworkSecurityRuleService class

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

This PR allows us to get at the storage account tables and read them. These tables are what store various bits of metrics data in Azure. You can get a list of the tables with the .tables method, or actually read and filter them with the .table_data method.
I also included some basic specs.

Added initial version of tables, table_info and table_data methods

---

lib/azure/armrest.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/role/assignment_service.rb
lib/azure/armrest/role/definition_service.rb
spec/role_assignment_service_spec.rb
spec/role_definition_service_spec.rb

This adds the Role::Assignment and Role::Definition service classes, along with corresponding model definitions. Some basic specs are included as well.

Add RBAC service classes

---

lib/azure/armrest/armrest_service.rb

We should no longer accept "preview" api version strings because they might not work.
This burned us when the VirtualMachineService tried to use '2016-04-30-preview' that Microsoft added today. The armrest gem tried to use that version, and the result was a BadRequestException.

Reject "preview" api versions

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb

This modifies the fetch_subscription_id singleton method so that it only allows **enabled** subscriptions. A minor update to the spec was also needed.

When fetching default subscriptions, only allow enabled subscriptions

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb
spec/armrest_service_spec.rb
spec/spec_helper.rb
spec/template_deployment_service_spec.rb

This adds proxy support to azure-armrest.
This required refactoring the rest_xxx methods internally to use a single generic function called rest_execute, which uses RestClient::Request.execute instead of the rest-client helper methods, which don't support parameters beyond the url and headers.
At the moment, the tests are failing however, and need to be refactored. I am not sure we really want the rest methods exposed as part of the API, either.

Add support for proxies, and refactor code to use new generic method.

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

* Added rest_head as instance and singleton methods.
* Added a proxy accessor to the Storage model class, and replaced RestClient calls with ArmrestService wrapper methods.
* Set Content-Type in the build_headers method once instead of individual methods.
* Added a proxy spec for the Storage class.

Add proxy support to Storage model

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/availability_set_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_group_based_subservice.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/resource_service.rb
lib/azure/armrest/storage_account_service.rb
lib/azure/armrest/template_deployment_service.rb
lib/azure/armrest/virtual_machine_extension_service.rb
lib/azure/armrest/virtual_machine_image_service.rb
lib/azure/armrest/virtual_machine_service.rb
spec/storage_account_service_spec.rb

This is largely a cosmetic update. I was just tired of typing out "armest_configuration", so I added a shorter alias and use it internally.
This will not only help save my fingers, it will potentially help avoid Rubocop warnings for lines being too long.

Add armrest_configuration alias

---

lib/azure/armrest/armrest_service.rb

Today @bronaghs discovered that MS set an api version string for VM's that's ahead of the current date (2016-03-30), and it's not a preview string either. The problem is that it doesn't work.
So, this patch will reject any api version strings that are ahead of the current date.

Reject api version strings that are ahead of the current date.

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/armrest_service_spec.rb

This PR adds the ArmrestService.configuration method. It returns whatever was sent to the ArmrestService.configure method. It also modifies the StorageAccount model's constructor to use the proxy information set in the configure method.
The primary motivation was to carry over the :proxy setting, which is not carried over automatically for the StorageAccount model because it makes its own http requests. However, setting this separately for every StorageAccount model object is cumbersome.
Note that I use a class instance variable, so subclasses will not have this information. It is easy enough to change if we would rather have it as a class variable and allow access for subclasses.

Modify the StorageAccountService class so that it sets the proxy on all StorageAccount models

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb

Minor tweak that calls .to_s on the proxy configuration setting (assuming it's not nil). I also added a spec.
This allows for URI objects as well as strings (or anything that responds to .to_s) for the :proxy option.

Allow URI objects for proxy settings.

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_spec.rb
spec/spec_helper.rb

This adds support for two more configuration options - ssl_verify and ssl_version, and passes these values to each http request.
By default the ssl_verify is set to nil, and the ssl_version is set to "TLSv1". As far as I can tell, rest-client is using SSLv3 by default, which is not great. Users can still configure the ssl_version if our default does not suit their needs.
Lastly, this fixes a potential bug in the configure + fetch_subscription_id logic where it wouldn't use the default proxy because it was being called before the default was set. That method should always be called last in the configure method.

Add support for ssl_version and ssl_verify config options

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/models/storage_account_spec.rb

We never added the ssl_version and ssl_verify options to the requests for the StorageAccount model. This addresses that and, like the proxy, uses whatever was set in the Armrest.configure, or TLSv1 for the ssl_version.

Add ssl_version and ssl_verify options to the StorageAccount model.

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

Before we were able to detect naming conflicts for a nested class. As a result a wrong class might be picked to be instantiated for a node.  Now use the fully qualified name of a nested class for testing whether it has been defined.

Fix checking whether nested class already exists

---

lib/azure/armrest/armrest_service.rb

Added a class method to clear class-level caches in ArmrestService.
This is needed when recording multiple VCR cassettes within a test -
as the tests need to clear the cache between exampes.

Added class method to clear caches.

---

lib/azure/armrest/insights/event_service.rb
lib/azure/armrest/model/base_model.rb
spec/insights_event_service_spec.rb

* add new `event_list` model that captures the list of the `events` and the `skip_token` if the list of events exceeds the API threshold (which is currently 200 events)
* return `event_list` model from `EventService#list` method
* add new `EventService#list_all` method to return all `events` matching the given `filter` and `select`ion by gathering all the pages of results and concatenating them together
* specs
@djberg96, @bzwei please review
/cc @Fryguy

Capture skip_token when listing events

---

lib/azure/armrest/insights/event_service.rb
spec/insights_event_service_spec.rb

Turns out the 'nextLink' property on the REST response for events is case sensitive, this PR changes 'nextlink' to 'nextLink'.
Also updated specs.

EventService - Changed 'nextlink' property on REST response to 'nextLink'

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/insights/event_service.rb
lib/azure/armrest/model/base_model.rb
spec/insights_event_service_spec.rb

Upon further discussion, we decided that we did not like the concept of an EventList class, as it would mean revamping the entire gem to handle skip tokens and lists to match that approach if we wanted to be consistent. Since that would cause serious breakage, this PR takes a different approach.
Within the list method, the last object (only) has the skip_token attribute set. The list_all method then looks for that token on the last object. This required adding the :skip_token attribute to the BaseModel, and modifying the list and list_all methods.
In addition, I added comments to warn users that you can only retrieve events for the last 90 days. Any more than that and you will get an error.
**Update**: we decided to revamp our approach, using a custom collection class (a subclass of Array …

Modify the Insight::Event list method and approach to skip tokens.

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

It turns out that when getting table data, the response contains duplicate keys, and this causes our auto-method generation to behave strangely. Apparently, the MS solution to get around duplicate keys was to change the case. For example, you will see this in a parsed json response:
```
{"Timestamp@odata.type"=>"Edm.DateTime", "Timestamp"=>"2016-03-24T17:00:07.671801Z", "Average"=>512583270.4, "Count"=>240, "CounterName"=>"\\Memory\\AvailableMemory","Last"=>512753664.0, "Maximum"=>512753664.0,"Minimum"=>511705088.0, "TIMESTAMP@odata.type"=>"Edm.DateTime", "TIMESTAMP"=>"2016-03-24T16:00:00Z","Total"=>123019984896.0}
```
Notice that "timestamp" and "timestamp@odata.type" appears multiple times, differing only in case. The result for an all caps key like this is that it generates …

Deal with all-caps response keys.

---

lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/insights/event_service.rb
lib/azure/armrest/model/storage_account.rb
spec/insights_event_service_spec.rb

This updates the StorageAccount#table_data method, which is currently broken. In addition, it was refactored so that continuation tokens are now supported, and query parsing and string generation is in its own method. I've also updated the documentation.
On a side note, the ArmrestCollection was modified to change the accessor "skip_token" to "continuation_token", because the former implies "$skip" in the query and a String object, which is not necessarily the case. I've updated the EventService class appropriately.

Fix and refactor the StorageAccount#table_data method

---

lib/azure/armrest/armrest_service.rb

This fixes a bug in the raise_api_exception method where we were trying to use Hash#fetch_path, which is not actually defined by active_support. We didn't notice this in standalone scripts because the error was getting swallowed and re-raised.
I've also added RestClient::Forbidden as an UnauthorizedException.

Replace fetch_path with regular key access in raise_api_exception

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/storage_account_service.rb
spec/models/storage_key_spec.rb
spec/storage_account_service_spec.rb

In the past we hard coded the api-version string for the StorageAccountService class because certain versions did not work. However, the latest version (2016-01-01) works fine and even provides additional information, so I've removed the '2015-05-01-preview' version setting.
However, this did cause some changes. First and foremost the ```list_account_keys``` and ```regenerate_storage_account_keys``` methods had to be updated since they no longer return a simple hash. Instead, they now return a list of StorageAccountKey objects.
To facilitate backwards compatibility, I've added 3 simple methods to the StorageAccountKey model - the key, key1 and key2 methods. Now, instead of calling ```hash#fetch('key1')```, it's just ```obj.key1``` or even just ```obj.key```, with the latter returning key1 …

Use latest api-version string for StorageAccountService

---

lib/azure/armrest/template_deployment_service.rb
spec/template_deployment_service_spec.rb

This removes the hard-coded api-version string for TemplateDeploymentService. Our changes in our api-version handler make this unnecessary. The current version is 2016-02-01.
I also updated the specs to use the current api-version string.
As far as I can tell, there have been no changes to the output. I tested all the get and list methods with some basic scripting and they seemed to work fine.

Remove hard coded api-version string for TemplateDeploymentService

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_config_spec.rb

Users will sometimes see "The access token is from the wrong issuer". This can happen if there are multiple AD's (tenants) on the same subscription, but then try to access data from a subscription that belongs to a separate tenant.
In our case the tenant used in the fetch_token method would be mismatched with a subscription picked up in the fetch_subscription_id method.
So, this modifies the fetch_subscription_id method to make a test request (looking for something with a relatively small response - tags) for each subscription. If it's invalid, it skips it and looks for the next one. It breaks out of the loop the first time it finds a valid one that is also enabled.
This will, of course, be a moot point in 0.3.0, but we should fix this for the 0.2.x branch.

Modify the fetch_subscription_id method so that it skips over unauthorized subscriptions

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

Because the `inspect` method was overridden, Ruby's PP module (and by extension `pry`'s pretty printer) would not pretty print any objects properly, instead leaving them on a single line which is hard to use.  This PR allows PP to work properly.
Before:
```ruby
$ bundle exec irb -Ilib -r"azure-armrest" -rpp
irb(main):001:0> o = Azure::Armrest::BaseModel.new({:name => 'test', :age => 33, :array => ["stuff"]}.to_json)
=> <Azure::Armrest::BaseModel name="test", age=33, array=["stuff"]>
irb(main):002:0> pp o
<Azure::Armrest::BaseModel name="test", age=33, array=["stuff"]>
=> <Azure::Armrest::BaseModel name="test", age=33, array=["stuff"]>
```
After
```ruby
$ bundle exec irb -Ilib -r"azure-armrest" -rpp
irb(main):001:0> o = Azure::Armrest::BaseModel.new({:name => 'test', :age => 33, :array => …
```

Add support for PP

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/virtual_machine_service.rb
spec/armrest_service_spec.rb
spec/configuration_spec.rb

Previously the whole caches are exposed. Now only provide query methods
to access cached data (for api-version and token)

Hide cache methods in Configuration class

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

An API change on the MS side has broken the validation for accountType because the request body has changed as of 2016-01-01.
Upon further review, I think it was misguided anyway. It is up to the users to know which account type they want, and the request response will contain an appropriate error message if it's invalid.

Remove storage account type validation and related specs.

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_spec.rb

This addresses https://github.com/ManageIQ/azure-armrest/issues/172
Basically, we can't delegate "list_providers" because that method doesn't exist in the Configuration class, and it wouldn't make sense to rename it, since it's just an instance variable.
I know we wanted to be consistent with the naming, but I think we should let this one slide. Also, it's how the current API works, so there's no breakage.

Fix delegation bug

---

lib/azure/armrest/armrest_service.rb

The cache_method library requires an `as_cache_key` method to work as part of its interface. We forgot about that, and we also changed the method name to `hash`.
This delegates the `hash` method to the configuration object in the base class, and creates an `as_cache_key` alias so that `cache_method` will work.
Addresses: https://github.com/ManageIQ/azure-armrest/issues/177

Delegate the hash method, and create an 'as_cache_key' alias

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/exception.rb

This just adds a TooManyRequestsException class that wraps a RestClient::TooManyRequests error. We will need this to handle errors caused by issuing too many requests in too short a time.

Add support for a TooManyRequests exception.

---

azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_service.rb
lib/azure/armrest/storage_account_service.rb

This PR replaces the uri standard library with addressable, which I've found is simply more robust and a better library in general. This was inspired by a recent issue that the azure-signature gem hit, which I want to avoid with this gem.
I also removed all calls to URI.escape since rest-client already auto-escapes, and made one minor doc update.

Replace uri with addressable

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/version.rb

This explicitly encodes all url's before passing them on to rest-client.
This is a "sort of" back-port for 0.2.x. In 0.3.x, we use Addressable::URI instead.

Call URI.encode on all url's before sending to rest-client.

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

This PR adds the StorageAccount#list_all_private_images method. This supercedes #187 that got goofed up somehow.
This is similar to StorageAccount#list_private_images, except that it uses a single call to get all storage accounts, which the user can filter, prior to making additional REST calls needed to get private images.
This is much more efficient, and effectively solves a problem where users would hit the request rate limit because they were iterating over too many resource groups.
All of the shared code was moved to private methods.

Add StorageAccountService#list_all_private_images method

---

lib/azure/armrest/availability_set_service.rb

It seems we can get all availability sets with the inherited list_all method now.

No longer need custom list_all method for AvailabilitySetService

---

.travis.yml

This limits our testing to Ruby 2.2.5 or 2.3.1.
Not only are older versions of Ruby mostly irrelevant, these are necessary to work with activesupport 5.x, and that's one of our dependencies.

Update travis.yml to only test Ruby 2.2.5 or later

---

spec/models/base_model_spec.rb

This fixes a failing spec for 2.3.x where the key ordering is not reliable. It limits the regex check and then just looks for specific strings.
Addresses https://github.com/ManageIQ/azure-armrest/issues/175

Don't depend on key order for pretty_print spec.

---

azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb

Addresses: https://github.com/ManageIQ/azure-armrest/issues/169
This replaces explicit `Thread.new` calls with `Parallel.each` calls, capping our thread pool at 10 threads per operation. It also adds a mutex for the `all_blobs` method (should have had one before) and updates the gemspec.
This is primarily for the benefit of the `list_in_all_groups` internal method, but is potentially useful elsewhere.

Use the parallel gem to cap our thread usage 

---

lib/azure/armrest/resource_group_based_service.rb

I thought the filtering option for the `StorageAccountService#list_all_private_images` was quite handy, and would be generally useful for the `list_all` method.
This lets users do things like `vms.list_all(:location => 'westus')`, which I think is quite handy.

Add a filter option to the list_all method.

---

lib/azure/armrest/configuration.rb
spec/configuration_spec.rb
spec/spec_helper.rb

This adds a Configuration#validate_subscription! method, and addresses https://github.com/ManageIQ/azure-armrest/issues/189.
The main issue is that the constructor effectively does a validation check for tenant ID, client ID and client key via the `fetch_providers` method, but it does not validate the subscription. This method allows users to explicitly validate the subscription and/or check to ensure that it's enabled.

Added Configuration#validate_subscription!

---

.travis.yml
lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

I want to backport the `list_all_private_images` method into 0.2.x. This will help solve https://bugzilla.redhat.com/show_bug.cgi?id=1342649 without having to upgrade the azure-armrest gem, which requires more substantial changes.

Add list_all_private_images to 0.2.x

---

lib/azure/armrest/configuration.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
spec/configuration_spec.rb

This adds a :max_threads option with a default of 10. This value is used internally as the value for any calls to Parallel.
Because of thread safety issues caused by the interaction of the Parallel and VCR gems, the default is reduced to 1 in a VCR environment.
There was also a minor change made to the StorageAccount#all_blobs method so that we can control the maximum number of threads there as well.

Add a :max_threads configuration option

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/resource_group_based_service.rb
spec/template_deployment_service_spec.rb

It turns out that the Azure REST API typically returns a 204 (empty body) on a DELETE operation for most resources if the resource does not exist instead of a 404 as you might expect. The net result is that you could call .delete on a resource multiple times and not realize that it didn't actually do anything. This PR specifically checks for a 204 and raises a ResourceNotFoundException if that's the response code.
More importantly, when calling delete we (eventually) want valid header information from the request that we can use to poll the resource because it's an asynchronous operation. If the resource does exist when we made the call to delete it, the header information will include a :location url attribute that we can use to poll the operation to see when it actually completes.
~~I'm …

Update delete method to handle 204 response.

---

lib/azure/armrest/configuration.rb

At the moment a proxy is not getting set prior to the call to validate_subscription, which can lead to failures, especially as rest-client still uses URI instead of Addressable.
This mistake effectively prevents Cloudforms from working with authenticating proxies at the moment.

Set proxy before calling validate_subscription.

---

lib/azure/armrest/exception.rb
spec/exception_spec.rb

This adds comments to the `Armrest::Exception` and `Armrest::ApiException` classes in exception.rb.
I also added a separate set of specs for the exceptions themselves.
The only real code change I made was to the `ApiException#to_s` method so that it includes the cause (if present), which should aid in debugging when one of our wrapper classes doesn't catch the underlying RestClient exception.

Add comments for exception classes, and update to_s method. 

---

lib/azure/armrest/exception.rb
spec/exception_spec.rb

This backports #210 into the 0.2.x branch. I commented out one test because that exception class doesn't exist here.

Backport custom Exception class updates into 0.2.x

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_spec.rb

This adds poll and wait methods to the base ArmrestService class. This lets us take the result of an asynchronous option (e.g. delete), and poll the resulting url header for its operations status. 
The wait method is just a sleepy loop around the poll method that would let users essentially "block until complete" for async operations.
This is part of the continuing effort towards a "delete_associated" method.

Add poll and wait methods.

---

.gitignore
lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/exception.rb
lib/azure/armrest/insights/event_service.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_service.rb
spec/armrest_collection_spec.rb
spec/insights_event_service_spec.rb
spec/models/storage_account_spec.rb
spec/template_deployment_service_spec.rb

This is a solution to https://github.com/ManageIQ/azure-armrest/issues/178.
This modifies the ResourceGroupBasedService so that the `list` and `list_all` methods return an `ArmrestCollection` object instead of a plain array. In turn, the `ArmrestCollection` object has been modified to include a `response_headers` accessor, and a `ResponseHeaders` model has been added as well, which is then set within the `list` and `list_all` methods.
*Update: the ResponseHeaders class was already added within a separate PR, so we use that now. Also, the method was changed from :headers to :response_headers.*
The short version is that now you can do something like this:
```
results = vms.list_all
results.response_headers.x_ms_ratelimit_remaining_subscription_reads
```
This lets us store the returned …

Modify the ResourceGroupBasedService to return ArmrestCollection objects.

---

lib/azure/armrest/storage_account_service.rb

Ignore any storage account that causes an exception to be thrown when its storage key is read. 
The list of errors that can be returned is documented here:https://msdn.microsoft.com/en-us/library/azure/mt163558.aspx
The BZ this will address is:
https://bugzilla.redhat.com/show_bug.cgi?id=1376468
Below is some sample back trace that applies to this BZ:
```[----] E, [2016-09-13T05:40:02.086088 #35846:c51994] ERROR -- : [Azure::Armrest::ApiException]: The storage account provisioning state must be 'Succeeded' before executing the operation.  Method:[rescue in block in refresh]
[----] E, [2016-09-13T05:40:02.086163 #35846:c51994] ERROR -- : /opt/rh/cfme-gemset/gems/azure-armrest-0.2.8/lib/azure/armrest/armrest_service.rb:442:in `raise_api_exception' …
```

Ignore storage accounts with keys that cannot be read.

---

lib/azure/armrest/storage_account_service.rb

This mimics #212 for the 0.3.x branch. In short, it skips over storage accounts where we cannot acquire a key, most likely because the provisioning is incomplete or failed for some reason.

Skip over storage accounts that have no key in list_all_private_images

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/resource_group_based_service.rb

This PR modifies the list and list_all methods in the ResourceGroupBasedService to support pagination.
Addresses https://github.com/ManageIQ/azure-armrest/issues/215.
~~~This required the addition of an accessor to the ArmrestCollection object called continuation_url, since it gives us a full URL instead of just a token.~~~
I also had to implement a new method that would not automatically encode the URL. This is because the URL is "pre-encoded" and encoding it again caused incorrect (and strange) results.

Update the list and list_all methods to support pagination.

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

Since we are already implementing the pretty_print method, we can rely
on the built-in pretty_print_inspect method, whose purpose is to
provide an inspect method directly from a custom pretty_print method.
This is a follow on from #165 , now I've learned a bit more about PP and found out about this pretty_print_inspect method.  By reusing that method, we can eliminate our custom inspect method entirely.
@djberg96 In the original PR, you were concerned it would affect AP, which it didn't.  Can you also verify it doesn't affect AP here as well?

Replace custom inspect with the one provided by pp.

---

lib/azure/armrest.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/resource_provider_service.rb

This deletes most of the code for the fetch_providers method. Instead, it now uses the ResourceProviderService#list method. Not only is the current code redundant, it doesn't cache the results. This causes a lot of unnecessary calls in the ManageIQ event runner, for example.
I opted to keep it a separate method for the sake of rspec testing. By keeping it separate, it's easier to stub responses for it.
The other change that was necessary was to default to nil in the provider_default_api_version method so that the set_service_api_version method can actually work properly.
Lastly I moved the cache_method require into the armrest.rb file where all the other libraries are required in case we want to use it within any other files.

Refactor the fetch_providers method

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/template_deployment_service.rb
spec/template_deployment_service_spec.rb

This adds the :get_template method to the TemplateDeploymentService class. This will allow us to get templates without resorting to inspecting deployment objects and then using raw URI calls.

Added the get_template method

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/exception.rb
spec/exception_spec.rb

Addresses https://github.com/ManageIQ/azure-armrest/issues/218
At the moment we're hard coding our exception classes in exception.rb, as well as rescuing and re-raising them individually in armrest_service.rb. While this works, whenever RestClient raises an error that we don't explicitly define, it defaults to ApiException.
Defaulting to ApiException is unfriendly for debugging purposes and leads to unnecessary guesswork, and there are a lot of exceptions that we don't define ourselves. This dynamically defines an exception class for each RestClient exception, and dynamically determines which one to use if an error is raised. The only ones we need to define ourselves are the ones that aren't defined by RestClient.

Dynamically define our own exception classes based on the RestClient

---

lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
spec/armrest_collection_spec.rb
spec/insights_event_service_spec.rb
spec/template_deployment_service_spec.rb

This adds a response_code accessor to our base model, sets it internally for our methods, and uses it within the poll method.
It also modifies the create method to return a response header object instead of a regular object since it's an asynchronous operation, and makes it consistent with the delete method.

Add response_code accessor and use it internally.

---

lib/azure/armrest/configuration.rb

This PR updates the `Configuration.clear_caches` method to clear the CacheMethod caches in addition to our own.
This is not only intuitive IMO, but also useful when regenerating VCR cassettes.

Clear all CacheMethod caches in the clear_caches method

---

lib/azure/armrest/resource_group_based_service.rb
spec/resource_group_based_service_spec.rb

This adds two methods to the ResourceGroupBasedService that will allow users to get objects based on an ID string without having to parse that information out themselves.
For example, a VM contains an ID for its NIC like this:
"id": "/subscriptions/xyz/resourceGroups/some_group/providers/Microsoft.Network/networkInterfaces/some_nic"
With that information we can then get a model object like so:
nic_id = vm.properties.network_profile.network_interfaces[0].id
vms.get_by_id(nic_id)
This will also make deleting associated resources easier.

Add get_by_id and get_subservice_by_id

---

lib/azure/armrest/resource_group_based_service.rb
spec/resource_group_based_service_spec.rb

This updates the parse_id_string method to handle hyphens and periods within resource groups and resource names, respectively. It also handles the "extension" service name, converting it to `VirtualMachineExtension`.
This is actually part 1 to fixing https://bugzilla.redhat.com/show_bug.cgi?id=1390715 because I need to get the extension information to get the correct storage account for metrics.

Update regex for parse_id_string, add support for extensions.

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_service.rb

This modifies the ResourceService so that a user may optionally retrieve all resources for the `:list` and `:list_all` methods. Currently the results are capped at 1000.
Because this could retrieve a lot of data for a subscription, a user must specify `:all => true` for this behavior.
This PR required moving the :get_all_resources and :model_class methods from the ResourceGroupBasedService class to the ArmrestService class. That way all service classes inherit those methods.

Modify the ResourceService list and list_all methods to get more that 1000 results

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/virtual_machine_service.rb

This PR adds the VirtualMachineService#delete_associated method. This will delete not only the VM, but resources associated with the VM as well. By default it will delete the NIC, the public IP, and the underlying image (vhd) file. You can optionally delete the network security group as well as the storage account that was backing it.
There's also a :verbose mode, in which case some extra logging is done. If there is no log, then STDOUT is used for the logger.
In cases where a user attempts to delete a resource that cannot be deleted (because something else is still attached to it), then it logs a warning and continues rather than failing. It is then up to the users to work out the issue, and delete the resource on their own.
I should add that we will need this for: …

Add method to delete associated resources

---

lib/azure/armrest/armrest_service.rb
spec/armrest_service_spec.rb

This adds a :service_name accessor. We store this information in an instance variable, e.g. "virtualMachines", but apparently never created an accessor for it.
This can be useful for URL building in internal methods.

Add a service_name accessor

---

lib/azure/armrest/billing/usage_service.rb
lib/azure/armrest/model/base_model.rb

This PR fixes the Billing::Usage model scoping (it was missing the Billing module), and updates the list method to return an ArmrestCollection instead of a plain array.
In addition, it now supports the `:all` option so that users can automatically retrieve more than 1k records. I also added a code example.

Fix Billage::Usage model and update Usage#list method

---

lib/azure/armrest.rb
lib/azure/armrest/configuration.rb
spec/configuration_spec.rb

This PR allows US Government clients to acquire the correct auth token by adding an :environment accessor. Government clients use a different endpoint URL, so the proper resource URL is used depending on the environment.
The use of the term "environment" lines up with both Powershell and the Azure CLI.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1403366
So in practice you could do:
conf = Azure::Armrest::Configuration.new(
:client_id   => 'xxx',
:client_key  => 'yyy',
:tenant_id   => 'zzz',
:environment => 'US Government'
)
vms = Azure::Armrest::VirtualMachineService.new(conf)
conf.environment = nil # would reset it to the public URL
vms = Azure::Armrest::VirtualMachineService.new(conf)

Add environment support

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/insights/diagnostic_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/subscription_service.rb
spec/configuration_spec.rb

This continues our goal of supporting US Gov for Azure by adding both `:resource` and `:authority` accessors to the Configuration class. If the `:environment` is set to 'usgov' then those accessors are set to the appropriate values automatically.
Service classes that were using the RESOURCE constants internally have been refactored to use the configuration accessor, and specs have been added.
Lastly, the resource for usgov needed a fix.

Add resource and authority accessors to Configuration class

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/virtual_machine_service.rb
spec/configuration_spec.rb

Ensure the RestClient.log to be an instance of Logger.
Move `VirtualMachineService#log_message` to base `ArmrestService` class. Slight modification - do not log anything unless the user provides a logger. Since this is a library, I feel we should not pollute console if the caller does not want to.
This common `log` method is private, meaning to be used internally by the service classes, not open to caller to write outside the gem.

Add a common log method to ArmrestService

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/virtual_machine_service.rb

With this refactoring the `wait` can wait without timeout limitation until the status actually turns into succeeded.

ArmrestService#wait accepts max_time = 0 to disable timeout

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/billing/usage_service.rb
lib/azure/armrest/insights/event_service.rb
lib/azure/armrest/insights/metrics_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_group_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/resource_service.rb
lib/azure/armrest/virtual_machine_extension_service.rb
lib/azure/armrest/virtual_machine_image_service.rb
spec/armrest_module_spec.rb
spec/armrest_service_spec.rb

This PR removes the Azure::Armrest::COMMON constant because it was tied to a specific resource. Instead, the ArmrestService#base_url method was altered to include "subscriptions/subscription_id", since this method was primarily intended for internal use.
All classes that used COMMON were refactored to use the updated build_url method, and the specs were updated as well. I also did some sanity checking to make sure all the changed service classes still worked properly.

Remove COMMON constant and modify base_url to include subscription

---

lib/azure/armrest/virtual_machine_service.rb

This fixes a bug for network security group deletion in the `delete_associated_resource` method. 
Currently, if a user chooses the option to delete a network security group, but one doesn't actually exist, the method crashes.

Fix for network security group deletion

---

lib/azure/armrest/resource_group_based_service.rb

Switch ending slash to leading slash. Fix the bug that cannot parse id without a subservice.

Fix regex for #parse_id_string

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/virtual_machine_service.rb

A change in `@base_url` caused some breakage in methods that weren't updated. Specifically, this broke the `tags` and `tenants` methods in the base ArmrestService class, as well as the `VirtualMachineService#series` method.

Fix breakage caused by change to base_url

---

lib/azure/armrest.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/environment.rb
lib/azure/armrest/insights/diagnostic_service.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/resource_service.rb
lib/azure/armrest/subscription_service.rb
spec/armrest_module_spec.rb
spec/armrest_service_spec.rb
spec/configuration_spec.rb
spec/environment_spec.rb

This PR adds an Environment class that contains all the relevant URL information. It is based mostly on the Azure endpoint mapping docs*, as well as some inspiration from one or two other Azure libraries out in the wild.
The Configuration#environment accessor now takes an instance of an Environment class instead of a string. Two pre-defined instances have been declared as well - Environment::Public and Environment::USGovernment. We can add more as needed later.
Most of the constants have been removed as they are no longer needed.
https://docs.microsoft.com/en-us/azure/azure-government-developer-guide#a-nameendpointaendpoint-mapping

Add Environment class and predefined Public and USGovernment instances

---

lib/azure/armrest/configuration.rb

For the `Configuration#subscription_id=` method, do not attempt validation or gather provider info if the argument is nil or blank since it will fail.

Explicit return if subscription ID is nil or blank

---

lib/azure/armrest/configuration.rb

This updates the `hash` method to include the environment name for cases where users are in mixed environments. Otherwise conflicts can arise from cached tokens that were generated for a  different environment.

Add environment name to hash method

---

lib/azure/armrest/insights/metrics_service.rb
lib/azure/armrest/model/base_model.rb
spec/insights_metric_service_spec.rb

This updates the MetricsService class so that it supports the newer API for metrics and metrics definitions.
The current `list` method, probably somewhat poorly chosen in hindsight, will remain for backwards compatibility. The `list_metrics` and `list_definitions` have been added to support the newer API. I kept the original method because it returns different output. The hardcoded api-version string is now only used for the older method.
In addition, I converted the `list` method to return an ArmrestCollection.
Originally written to try to work get metrics working for usgov regions (it still doesn't), this is a much easier way to get metrics information for public environments than our current approach, which requires accessing the storage account directly.

Update MetricsService class to include newer REST API

---

lib/azure/armrest/resource_provider_service.rb
spec/resource_provider_spec.rb

This PR adds the `registered?` method to the ResourceProviderService class. This is basically a shortcut for:
ResourceProviderService#get(namespace).regisration_state == "Registered"
But with case and exception handling baked in.
This will be useful in our effort to disable events and metrics collection for ManageIQ in unsupported regions.

Added the registered? method

---

Gemfile
azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/resource_provider_service.rb

@djberg96 Please review.  I've chosen memoist because it solves the same problem of "caching methods that have parameters", but it just uses "normal" memory memoization via ivars under the covers.  Additionally, it's already a dependency of manageiq (we use it for caching of Relationship records).
Note that this removes the `cache_time` class accessor method.  I don't see it used anywhere in manageiq nor in manageiq-providers-amazon, which means it must always be defaulting to 24 hours.  At 24 hours for a instance method cache, that's practically infinity, so I'm not sure what purpose it actually serves.  Additionally, it was implemented as a class-level shared timeout, even though setting it is at an instance level, which is strange.
The first commit was just so I wouldn't get "double …

Replace cache_method with memoist gem

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

This PR deals with the possibility that a json key might have a space in it in the BaseModel class. Somewhat surprisingly, it turns out the `.underscore` method does NOT convert spaces to underscores. So, we have to do it manually, or we can't auto generate a model and/or method name for it.
Thus, a key of "foo bar" will be converted to "foo_bar".
Addresses https://github.com/ManageIQ/azure-armrest/issues/264

Explicitly handle the possibility of a space in json key

---

spec/configuration_spec.rb

This PR fixes an issue where log cleanup was failing on Windows when running the specs. By removing the mixture of `let` with `after`, moving those bits into the relevant context, and using a dup of $stdout instead of plain STDOUT, I was able to perform proper cleanup.
While this wasn't an issue on unixy systems, this is still a better testing approach with rspec in general.
Addresses https://github.com/ManageIQ/azure-armrest/issues/259

Refactor logger specs to fix Windows failures

---

azure-armrest.gemspec

This PR upgrades the Nokogiri dependency from 1.6.x to 1.7.x. This addresses complaints from Hakiri which indicated that there have been security patches to nokogiri/libxml2.
See CVE-2016-4658 for details:
http://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2016-4658
Both this PR and https://github.com/ManageIQ/manageiq-gems-pending/pull/117 should be merged together.

Upgrade Nokogiri to 1.7.x

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

In order to maintain interface compatibility with existing to_json methods, we must add an options argument to the `to_json` method. Otherwise, attempting to call `to_json' on an array of model objects will fail.
Addresses https://github.com/ManageIQ/azure-armrest/issues/270

Add an options argument to BaseModel#to_json

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/storage/disk_service.rb
spec/storage_disk_service_spec.rb

This allows us to get the raw blob data for a VM that's backed by a managed disk instead of a storage account. I also added a ResponseBody model for convenience.
This is similar to the StorageAccount model method  of the same name but there are some internal differences. Mainly, this method requires multiple calls internally to work.
Addresses https://github.com/ManageIQ/azure-armrest/issues/268
~~~WIP for now until I can get some specs made. I may also want to call `EndGetAccess` explicitly, but I'm not sure yet.~~~

Add get_blob_raw method.

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/virtual_machine.rb
spec/models/virtual_machine_spec.rb

This just adds some convenient shortcut methods for the VirtualMachine model. They are:
* managed_disk?
* size (alias: flavor)
* operating_system (alias: os)

Added some convenience methods to the VirtualMachine model

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

At the moment we have an `Object#resource_group` method but no `Object#subscription_id` method.
This PR adds a subscription_id method, and improves the existing regex for `resource_group` to account for the possibility that the trailing slash and/or more characters might not be present.

Add subscription id to BaseModel

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

This adds the `update_blob_properties` to the `StorageAccount` model. The main reason for adding this is to add the ability to resize a blob. This may be desired for older .vhd files that are no longer a "valid" size according to current Azure standards.
I've also updated the internal api version. Look here for a list of changes:
https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services
I lowercased and stringified the header information to be consistent with the azure-signature gem as well, which prevents potential duplicates.

Add the StorageAccount#update_blob_properties method

---

lib/azure/armrest/storage_account_service.rb

At the moment the custom objects we generate for the `list_private_images` method do not include a resource group. This PR explicitly sets it, using the underlying storage account's resource group as its source.

Explicitly add the resource_group for private images

---

azure-armrest.gemspec

Addresses a CVE for Nokogiri/libxslt:
https://www.ubuntu.com/usn/usn-3271-1/

Update nokogiri dependency to 1.7.2

---

lib/azure/armrest/environment.rb
spec/environment_spec.rb

This PR adds Environment objects for both China and Germany. This will let us support more Azure regions in the ManageIQ app as well.
I also added some specs.

Add predefined Environments for Germany and China

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

When we first wrote the StorageAccount model, the Azure API included `key1` and `key2` in the output when getting information for individual storage accounts. Consequently, the `key` argument for most of the methods defaulted to `properties.key1` if a key wasn't explicitly provided.
However, Microsoft later removed this information from the JSON output, requiring a separate request to get access key information. The oldest supported api-version string (2015-05-01-preview) does not include this output, so there is no point keeping it around. On the contrary, if you don't provide a key explicitly, you will get a cryptic error message about there being no "key1" property.
This PR does three things. First, it adds an `access_key` accessor, so that you can set it once for that particular …

Remove check for key1, add access_key accessor

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

The `StorageAccount#all_blobs` method should allow a hash of options. This is then passed to the `StorageAccount#blobs` method as part of the call when collecting blobs.

Allow the all_blobs method to accept an options hash

---

lib/azure/armrest/model/storage_account.rb

The current `create_blob_snapshot` doesn't support any options. This adds support for them. It also changes the returned value from a `BlobSnaphot` object to a `ResponseHeaders` object since it's an asynchronous method.
I have also updated the `create_blob` method to support more options, and updated the documentation. Here I also changed the returned object to a `ResponseHeaders` object.
Because I am changing the return object for both of these methods, I will bump the version to 0.8.0 if/when this is merged.

Revamp the create_blob_snapshot method

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
spec/armrest_service_spec.rb

The ArmrestService#locations method originally iterated over the providers list because I didn't think there was a direct way to get a list of supported locations. The only documentation I could find applied only to classic Azure. However, it turns out that you *can* get a list of locations directly.
Consequently I would like to refactor the ArmrestService#locations method so that it returns a list of Location objects. Also, to be consistent with our other methods, change the method name to `list_locations` with a deprecated alias for backwards compatibility. Here's an example of what the proposed method returns:
"id"          => "/subscriptions/xxx/locations/koreasouth",
"name"        => "koreasouth",
"displayName" => "Korea South",
"longitude"   => "129.0756",
"latitude"    => "35.1796" …

Refactor the locations method

---

lib/azure/armrest/virtual_machine_image_service.rb
spec/virtual_machine_image_service_spec.rb

Essentially just the commit message. This adds a list_all method to the ```VirtualMachineImageService``` class. This method is used in ManageIQ/manageiq-providers-azure#95

Add list_all method to VirtualMachineImageService

---

lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

At the moment we don't have any support for the File Services API. This adds the following methods to the `StorageAccount` model:
* create_directory
* delete_directory
* directory_properties
* directory_metadata
* create_file
* delete_file
* copy_file
* file_properties
* file_metadata
* files
* file_content
* add_file_content

Wrap the File Services API

---

lib/azure/armrest/storage/disk_service.rb

The `DiskService#get_blob_raw` method has a bug when :start_byte and :length are used together. This fixes that.

Fix start_byte + length options in DiskService

---

lib/azure/armrest/template_deployment_service.rb
spec/template_deployment_service_spec.rb

This adds the `exists?` method to the `TemplateDeploymentService` class. Ideally we could use this method to speed up template collection, as well as reduce memory, since it uses a HEAD request.

Add TemplateDeploymentService#exists? method

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/resource_group_based_service.rb

At the moment, any resource group based service that calls `create` must match the hash keys to the actual parameters used by Azure. This means they must be in `camelCase` format, so the `options` hash to a `create` currently must look something like this:
```
:properties => {
:hardwareProfile => { :vmSize => 'Standard_A0' },
:osProfile => {
:adminUserName => 'dberger',
:adminPassword => 'Smartvm123',
:computerName  => 'miqazure-wincpy'
},
}
```
With this change users could write `:hardwareProfile` or `:hardware_profile` interchangeably and it would Just Work.
One less thing to worry about. :)

Automatically camelize hash keys in the create method

---

lib/azure/armrest.rb
lib/azure/armrest/key_vault_service.rb
lib/azure/armrest/model/base_model.rb
spec/key_vault_service_spec.rb

This PR adds the KeyVault service class and specs. This could potentially be used for the Azure provider keys option.

Add the KeyVaultService class

---

lib/azure/armrest/storage_account_service.rb

This is a followup to https://github.com/ManageIQ/azure-armrest/pull/291. We have a separate method for listing private images, so we should apply a caseless filter to that as well.

Make private image filter caseless for strings

---

lib/azure/armrest/resource_group_service.rb
spec/resource_group_service_spec.rb

Adds the ResourceGroupService#exists? method. Unlike a `get` this is a faster HEAD request, and only returns a boolean value.

Add the ResourceGroupService#exists? method

---

lib/azure/armrest/storage/disk_service.rb
lib/azure/armrest/storage/managed_storage_helper.rb
lib/azure/armrest/storage/raw_blob_helper.rb
lib/azure/armrest/storage/snapshot_service.rb
spec/storage_snapshot_service_spec.rb

Add ability to read Snapshots taken for Managed Disks.
We add get_blob_raw for the Snapshots which mirrors the code for
Managed Disks themselves via the Storage DiskService.
A common helper file raw_blob_helper.rb with the RawBlobHelper
module is added to be used by the DiskService and SnapshotService.
In addition the EndGetAccess operation must be performed when each read
operation is finished so that an attempt to remove the Snapshot will succeed.
These changes as discussed with @djberg96.  @djberg96, @roliveri please review and
merge when appropriate.  Thanks.  Other PRs for manageiq-providers-azure  that depends
on this one and manageiq  are forthcoming.
The following BZ depends on this change: https://bugzilla.redhat.com/show_bug.cgi?id=1459612

Add get_blob_raw for Managed Disk Snapshots

---

lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/template_deployment_service.rb

This adds the option of a filter to the `TemplateDeployment#list_all` option, which in turn modifies the underlying `list_in_all_groups` private method. Applying a filter up front could reduce the time and memory currently consumed by collecting deployment information.
This is part of the effort to help fix https://bugzilla.redhat.com/show_bug.cgi?id=1431912.

Add filter to TemplateDeploymentService#list_all

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/resource_provider_service.rb

This PR allows the `list` and `list_all` methods to accept a hash of options that could potentially modify the results. The possible options are `:top` and `:expand`.
It also fixes an issue I ran into when I used the `:expand` option, which is that a hash key with a "." in it would blow up our model generator. This converts them to underscores.

Allow options to the list and list_all methods for ResourceProviderService

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb
spec/models/storage_account_spec.rb

Currently we are only passing specific parameters to each StorageAccount object from the Configuration object. This PR modifies the StorageAccountService and StorageAccount model classes so that the full configuration object is passed along.
This eliminates the need for separate accessors for each property, and makes it easier to handle configuration properties that we may need to handle in the future within the model. For example, I want to add a `:timeout` property to the Configuration object that I will need to pass along to the models. With this approach, the model will automatically have access to it.

Modify the StorageAccountService class to pass full configuration object to model

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb

This adds the Configuration#max_retries accessor. This, in turn, controls the maximum number of retry attempts on 429 and most 50x errors.
The `rest_execute` method is then modified to automatically retry X number of times (default: 3) if a 429 or 50x HTTP error code occurs. The 429 error is returned if the user exceeds their rate limit. The 50x errors that I rescue are server side issues that are typically temporary and transient.
For both 429 and 503 errors the server will return a `Retry-After` header that we can use to determine the amount of time we should sleep between tries. If that header isn't found, it defaults to 30 seconds. If a logger object is set, a warning is logged as well.
Update: I've added 409 (Conflict) as well since it can happen with blob operations.

Add max_retries accessor and retry on rest_execute in certain conditions

---

lib/azure/armrest/configuration.rb
spec/configuration_spec.rb

This removes token caching from the Configuration object. Originally this was added when configuration information was part of the ArmrestService class. However, since it's a separate object now, and each Service constructor receives a configuration object that stores its own token information, I don't believe it serves much of a purpose any longer.

Remove token caching

---

lib/azure/armrest/configuration.rb
spec/configuration_spec.rb

I want to revert this for now as to avoid backwards compatibility issues. If possible, we should create a "0.9.0" milestone and tag it with that.

Revert "Remove token caching"

---

lib/azure/armrest/storage_account_service.rb

The `ResourceGroupBasedService#list_all` method, which the `StorageAccountService` inherits from, has the exact same filter code in place as what is used in the `list_all_private_images` method, so use that instead of maintaining duplicate versions of this code.
Found this while poking around in the gem, so thought I would make a quick PR to address.  All of the tests seem to pass with these changes in place.  Will do some testing where I know this is used to also confirm the same functionality.

Use filter from list_all (remove duplicate code)

---

lib/azure/armrest/model/base_model.rb

When calling `Object.methods`, we are generating an array of symbols (maybe strings as well) every time to determine every one of the public and protected that exist on the given target, and this is generated every time this is called (though don't quote me).
By using `respond_to?`, we are avoiding generating that array, and simply determining if that method is defined and not the definitions of any other methods.
Benchmarks
----------
When making a call to `.list_all` of the storage accounts from an example azure account, the difference after this change was applied can easily be shown (metrics gathered using the `memory_profiler` gem):
**Before**
```
Total allocated: 25509365 bytes (198470 objects)
Total retained:  37155 bytes (353 objects)
allocated memory by gem …
```

Use respond_to? instead of methods.include?

---

lib/azure/armrest/model/base_model.rb

The `@json` field in any `BaseModel` based classes is only used when inspecting the object or converting the `@hash` value to a json string (this only happens when the object is instantiated using a json string instead of a ruby Hash).
In most cases, this means that the `@json` that is instantiated is never actually accessed, so deferring the call to `.to_json` on `@hash` to when it is actually used improves performance in most cases.
Benchmarks
----------
Notice the change in the number of allocations for `String` and `JSON::Ext::Generator::State`:
**Before**
```
Total allocated: 18764397 bytes (192606 objects)
Total retained:  37091 bytes (352 objects)
allocated memory by gem
-----------------------------------
8487284  azure-armrest/lib
7396499  activesupport-5.0.6
2164831  json-2.0.4 …
```

Lazy load json strings when possible

---

lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/armrest_service.rb

Currently, when the `ArmrestService#get_all_results method` is called, it parses the response body (as JSON) once when instantiating the ArmrestCollection, and a second time to determine the `'nextLink'` value for the subsequent `while` loop to get the remaining results (this is duplicated as well for each iteration of the loop).
Since we now have a `next_link` variable on the `ArmrestCollection` instances that is determined in the same fashion from the first `JSON.parse`, we can use that instead of duplicating the same effort twice.
Benchmarks
----------
In practice, this halved the allocations caused by the JSON gem (when using the one from ruby stdlib), and 10% of the total object allocations over all when calling `StorageAccountService#list_all_private_images` on a small to moderate …

Use ArmrestCollection#next_link in get_all_results

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/storage/managed_storage_helper.rb
spec/storage_disk_service_spec.rb
spec/storage_snapshot_service_spec.rb

This revamps the get_blob_raw method to use a proper `wait` approach on the `BeginGetAccess` call, and bails after two minutes if unsuccessful. The various `try` blocks are unnecessary now, since they were an artifact of trying to reference properties before we actually succeeded in getting access.
This also updates it so that the `EndGetAccess` call is only made if the `BeginGetAccess` call was successful.
In addition, it modifies the `wait` method to accept a `wait_interval` argument (default 10 seconds), and updates the specs.

Refactor get_blob_raw method

---

lib/azure/armrest/armrest_service.rb

This fixes an issue in the `rest_execute` method where I accidentally tried to use the instance level `log` method, which doesn't work. Instead, we use the singleton method to access the log, and log a message if it exists.
In addition, I added the http err code to the log message.

Fix singleton level logging

---

lib/azure/armrest/model/storage_account.rb

The `log` method isn't available to model objects, so we have to use the Configuration singleton method within the StorageAccount class.

Logger fix for StorageAccount

---

azure-armrest.gemspec

Updates the parallel gem from 1.9 to 1.12, which includes a fix from none other than Joe R as well.
Also, I got rid of the `$LOAD_PATH` mangling, and just use `require_relative` instead.

Upgrade parallel gem to 1.12.x, use require_relative

---

lib/azure/armrest/resource_group_based_service.rb
spec/resource_group_based_service_spec.rb

This updates the internal `parse_id_string` method, which is used by the `get_by_id` method, to ignore case.
This came up because we use a lowercased version of the id string for the ems_ref in ManageIQ, which would then fail on the `get_by_id` method.

Update the parse_id_string method to ignore case

---

azure-armrest.gemspec

There is currently a CVE out for `libxml2`, that affects `nokogiri`:
https://access.redhat.com/security/cve/cve-2017-9050
Unfortunately, so projects that depend on `azure-armrest` expect that the version of nokogiri is within the `1.7.x` release.  To allow for that (as insecure as it is), but make sure we try to use the latest version of `nokogiri` when possible, relax the version requirement on this gem so that we are secure as we can be without breaking other projects.
That said, we probably should make nokogiri-1.8.1 a minimum requirement in the v1.0 release though.

Relax nokogiri gem version

---

.rubocop_local.yml
lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
spec/models/base_model_spec.rb
spec/models/storage_account_spec.rb
spec/models/storage_key_spec.rb

The intent of this PR is to introduce a flag into the initializer of each `BaseModel` backed class, currently called `skip_accessors_definition`.
The intent of this is that it can be used internally to avoid calling `__setobj__` on objects initially, which is useful for methods like `StorageAccountService#list_all_private_images`, which uses multiple intermediate objects/api calls to get the end result, and calling __setobj__ on each one of those is expensive and resource intensive, especially when they don't need to be used by the end user.
Some helper methods also needed to be introduced to allow for safe access of properties that were in nested hashes.  To save on resources, I avoided using `.with_indifferent_access` to the `@hash` value of the `BaseModel`, but that might have made …

Light base model mode

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

Apparently it's possible for the keys returned by the `TemplateDeploymentService#list_deployment_operations` to contain a key with a "$" in it. Since we have no idea where else this could potentially happen, we need to account for that possibility anywhere. So, it is now replaced with a "_" as well.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1495318
I added some specs and fixed one unrelated spec description while I was in there.

Handle possibility of dollar sign in key for model generation.

---

.rubocop_local.yml
CHANGES
lib/azure/armrest/armrest_collection.rb
lib/azure/armrest/armrest_service.rb
lib/azure/armrest/model/base_model.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb
lib/azure/armrest/version.rb
spec/models/base_model_spec.rb
spec/models/storage_account_spec.rb
spec/models/storage_key_spec.rb

This backports the lite model changes from 0.9.0 to 0.8.5, so that we can get those changes in without the nokogiri changes.
We never squashed those commits so it required cherry picking 7 commits, but it's all here and the specs all pass.
https://github.com/ManageIQ/azure-armrest/pull/319/commits
I've updated the version and change files, too.

Backport lite model changes

---

.travis.yml

The ManageIQ core repo removed Ruby 2.2.x from their test matrix, so I think we should, too.
https://github.com/ManageIQ/manageiq/blob/master/.travis.yml

Remove 2.2.x from test matrix.

---

.travis.yml

Reverts ManageIQ/azure-armrest#337
Let's wait until March 2018 to remove this.

Revert "Remove 2.2.x from test matrix."

---

azure-armrest.gemspec
lib/azure/armrest/model/storage_account.rb
spec/models/storage_account_spec.rb

We're already using `Hash.from_xml` from the `activesupport` library. It turns out, that's really all we need. This eliminates the need to explicitly require nokogiri, or any xml parsing library for that matter, as a dependency.

Remove nokogiri, just use activesupport

---

azure-armrest.gemspec

This allows any 2.x version of the json gem. We don't need to be more strict than that IMO.

Loosen restriction on json dependency.

---

lib/azure/armrest/armrest_service.rb

The `err.response.headers[:retry_after]` value is a stringified number instead of a plain number, so we must explicitly call `.to_i` on the value to `sleep` or an error will occur.
Note that we already do this for the `wait` method.

Ensure value passed to sleep method is an integer

---

lib/azure/armrest/version.rb

This updates the latest version of the azure-armrest gem.
Not sure why the file previously has the version set to 0.8.5 when we have already released 0.8.6 - see https://rubygems.org/gems/azure-armrest - Likely an oversight.

[FINE] version update for 0.8.7 release

---

CHANGES

Updates the CHANGES file with the change included in 0.8.7
I noticed 0.8.6 is not included in this file, but I did not want to add an entry because I do not see the [PR](https://github.com/ManageIQ/azure-armrest/pull/329) in the 0.8.x commit log
@djberg96 - can you investigate?

[FINE] Changes for the 0.8.7 release

---

lib/azure/armrest/model/base_model.rb

Ruby already has a mechanism in place for getting the callstack path locations and line numbers that doesn't require string splitting/parsing.
This also fixes a bug on Windows systems when trying to split callstacks with file paths in them, since most windows file paths include something like 'C:/path/to/file', which has an additional ':' that is not expected by the codebase.
Fixes some of https://github.com/ManageIQ/azure-armrest/issues/332
cc @djberg96

Use caller_locations instead of caller

---

lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/storage_account_service.rb

When speeding up the `list_all_private_images` method, the `list_all` method was updated with the `skip_accessors_definition` boolean flag to that and associated methods.  This was not, though, applied to the `StorageAccountService#list_private_images` method, which works on just a single storage account instead of all of them.
This updates `#list` in both the `StorageAccountService` version, and the base class to allow it to support this flag.
Links
-----
* https://bugzilla.redhat.com/show_bug.cgi?id=1506667
* Introduced in https://github.com/ManageIQ/azure-armrest/pull/319

Fix StorageAccountService#list_private_images

---

spec/fixtures/unmanaged_storage_accounts.json
spec/fixtures/vms.json
spec/storage_account_service_spec.rb
spec/virtual_machine_service_spec.rb

This is meant as a followup to https://github.com/ManageIQ/azure-armrest/pull/345.
This adds specs for the list and list_all methods for both StorageAccountService and VirtualMachineService. It includes specs for skipping the accessor definitions as well.

Added some specs for list and list_all methods

---

lib/azure/armrest.rb
lib/azure/armrest/hdinsight/application_service.rb
lib/azure/armrest/hdinsight/cluster_service.rb
spec/hdinsight_application_service_spec.rb
spec/hdinsight_cluster_service_spec.rb

This removes what feels like a redundant "HDInsight" as part of the name, since these classes are already scoped.

Rename the HDInsight classes

---

README.md
lib/azure/armrest/virtual_machine_service.rb

An example in the README currently refers to a variable that hasn't been set, so I updated that example. Also, the VirtualMachineService has some incorrect documentation (it has the default provider and optional provider backwards).

Updated README and VirtualMachineService documentation

---

lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/storage_account_service.rb

When we switched over to the `skip_accessors` approach, we missed a couple places where the `.name` property isn't available. Instead, we must use `name_from_hash`.

Use name_from_hash in exception handlers

---

lib/azure/armrest/storage/managed_disk.rb
lib/azure/armrest/storage/managed_storage_helper.rb
spec/storage_disk_service_spec.rb
spec/storage_snapshot_service_spec.rb

Azure Managed Disk Instances have been taking exceptionally long in
some locations.  It turns out that the semantic that azure-armrest
uses to perform reads via the get_blob_raw method is the culprit.
The method gets a SAS URL - an access token to the disk - each
time it performs a read operation.  The call to get the access token
is asynchronous and if it does not return immediately with success when
poll is called the gem sleeps for 5 seconds.  This adds 5 seconds to
*every* call to get data.
get_blob_raw is being left in the gem for compatibility purposes.
However the new semantic is this:
Call open on the service (disk service or snapshot service).
Open returns a ManagedDisk object.
Call read on the ManagedDisk object as many times as you need, then call
close on the ManagedDisk …

Managed Disk Read Semantics Change

---

lib/azure/armrest/model/base_model.rb
spec/models/base_model_spec.rb

Similarly to commit 845d11a (pr 329) it is possible for a colon to be present in keys of a BaseModel.  This patch allows for colons to be converted to underscores like we do for periods and dollar signs.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1548153

Handle possibility of colons in keys for model generation.

---

lib/azure/armrest/resource_group_based_service.rb

This adds `get_by_id` for both TemplateDeployment's and TemplateDeploymentOperation's.
This will be useful as part of the targeted refresh effort.

Implement get_by_id for TemplateDeployment and TemplateDeploymentOperations

---

lib/azure/armrest/resource_group_based_service.rb
spec/resource_group_based_service_spec.rb

This raises an explicit error, and gives us a nicer error message, if the ID string pased to `get_by_id` is invalid. Otherwise you'll get a cryptic `undefined method 'names' for NilClass`.
This came up during the targeted refresh overhaul for Azure.

Explicitly raise an error in get_by_id if the ID string is invalid

---

lib/azure/armrest/storage_account_service.rb

Turns out there's no `container_from_hash` method on a Blob object, just the regular hash accessor. So, we need to fix that. Otherwise we'll get:
`undefined method 'container_from_hash' for #<Azure::Armrest::StorageAccount::Blob`

Fix the error message if the get_private_images method fails

---

lib/azure/armrest/storage_account_service.rb
spec/storage_account_service_spec.rb

This PR adds the `StorageAccountService#get_from_url` method. This is handy when you have a storage account endpoint like `http://foo.blob.core.windows.net/vhds/some_file.vhd` and want to get information on the storage account that's backing it. I also updated the `get_from_vm` method to take advantage of this new method since it's more generic, and more efficient.
This will be a handy method to have as part of the targeted refresh update.

Added the get_by_url method to StorageAccountService

---

lib/azure/armrest/virtual_machine_image_service.rb

This updates the `VirtualMachineImageService#list_all` method to use multiple loops via the Parallel library in order to significantly speed up the results. Currently this method takes over 20 minutes without threading. With threading the time drops down to about 1 minute to collect all results.
Addresses https://github.com/ManageIQ/azure-armrest/issues/306

Use parallel for nested loops in VirtualMachineImageService#list_all method

---

lib/azure/armrest/configuration.rb

It would seem that for initial authentication and token generation, we should be using the ActiveDirectory URL instead of the resource manager URL to get a token.
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code
Normally this doesn't matter when authenticating against Microsoft Azure, but it comes into play when using Azure Stack.

Change the resource URL to the active directory URL

---

azure-armrest.gemspec

In order to upgrade `fog-google` in google provider, it is required to upgrade the `addressable` in azure as well.
Dependency chain:
- [`"fog-google", "~> 1.3.3"`](https://github.com/ManageIQ/manageiq-providers-google/pull/54)
- [`"google-api-client", "~> 0.19.1"`](https://github.com/fog/fog-google/blob/ee58e2a4d9502f2a4dc102ca6a4b664656551e3f/fog-google.gemspec#L28)
- [`"addressable", "~> 2.5", ">=2.5.1"`](https://github.com/google/google-api-ruby-client/blob/38e271cfb4532d61b857f624478108592288da06/google-api-client.gemspec#L25)
Related: https://github.com/ManageIQ/manageiq-providers-google/pull/54

Update `addressable` gem version to 2.5.0

---

lib/azure/armrest/virtual_machine_extension_service.rb

Back in 2015 there was a bug in the Azure with regards to listing extensions for a VM. That is apparently no longer true, as I was able to make it work without issue today.
In addition, I refactored the code a bit to use our `Armrest::Collection` class instead of doing things the hard way.

Update VirtualMachineExtension#list method

---

lib/azure/armrest.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/template_deployment_service.rb
spec/resource_group_based_service_spec.rb
spec/template_deployment_service_spec.rb

In version 0.8.2 we added the ability to allow either `lower_case` or `camelCase` options for the `create` method. This convenience was handy and consistent with our model generation methods.
However, this caused a bug in the `TemplateDeploymentService#create` method where you don't actually want to transform keys in templates, but keep them as-is, because they aren't interchangeable.
This PR fixes the issue by updating the `ResourceGroupBasedService` and `TemplateDeploymentService`. From now on it will use the private method `transform_keys?` internally to check to see if the keys should be transformed first. Individual subclasses can override this method simply by redefining it to return `false`.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1568009
Update: as per Bill's request, …

Add a customizable method that can disable key transformation

---

lib/azure/armrest/resource_provider_service.rb
spec/resource_provider_spec.rb

This PR adds a convenience method to check to see if a particular resource type is supported. This is potentially useful for other environments, such as USGov or Azure stack environments, where some of their public features are not supported.
Part of a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1566600

Added the ResourceProviderService#supported? method

---

lib/azure/armrest/environment.rb
lib/azure/armrest/model/base_model.rb
spec/environment_spec.rb

This adds an `Environment.discover` method that, when it receives an endpoint, will automatically retrieve the metadata that Azure provides in order to create a custom `Environment` object with its own set of custom endpoints. This environment can then be passed to the `Configuration.new` method.
Example:
```
env = Azure::Armrest::Environment.discover(:url => "https://some_endpoint")
Azure::Armrest::Configuration.new(:environment => env, ...)
```
The main purpose here is to alleviate the pain for Azure stack environments where users would have to manually create their own environments, and hard coding them might break. This could be also used for any other public environments Microsoft introduces in the future that aren't already pregenerated as well.
Addresses …

Add an Environment.discover method

---

.rubocop_local.yml

For some reason rubocop is complaining about the lack of parens for `raise` calls, even though the file we inherit from explicitly says to ignore them. Putting parens around `raise` is also invalid syntax, so I've added it to our `rubocop_local.yml` file, and that seems to have fixed it.
Also, I prefer `[]` to `()` for arrays of things, since it matches the Ruby syntax.

Modify rubocop - ignore raise for parentheses, and use [] for arrays of things.

---

lib/azure/armrest/model/base_model.rb
lib/azure/armrest/virtual_machine_image_service.rb
spec/virtual_machine_image_service_spec.rb

This PR adds three methods to the `VirtualMachineImageService` class.
* extension
* extension_types
* extension_type_versions
These methods give us insight into the available extensions, e.g. LinuxDiagnostics, that we can use to help us automatically add diagnostic information when provisioning a virtual machine in ManageIQ.
Needed for https://bugzilla.redhat.com/show_bug.cgi?id=1494032

Add vm image extension methods

---

lib/azure/armrest/armrest_service.rb
lib/azure/armrest/configuration.rb
lib/azure/armrest/model/storage_account.rb
spec/configuration_spec.rb
spec/spec_helper.rb

This PR adds a :timeout option that is passed along to each rest-client http request. I've set the default value to 10 seconds for now.
I've tested several of our methods, including private image collection and raw blob data, and it seems to be fine with that value. It can always be configured, too.

Add a :timeout option that is passed along to all http requests

---

.rubocop_local.yml

Explicitly stringifying the delimiters seems to make the current rubocop bugs go away.

Quote delimiters to deal with rubocop bug

---

lib/azure/armrest/environment.rb
spec/environment_spec.rb

Updated endpoint as Azure Government has changed their endpoint as indicated here:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide
Addresses bug: https://bugzilla.redhat.com/show_bug.cgi?id=1627520

Updated endpoint settings for Azure Government per bug 1627520 

---

lib/azure/armrest/key_vault_service.rb
spec/key_vault_service_spec.rb

This PR adds two methods to the `KeyvaultService` class.
This might be useful down the road for provisioning with stored pub keys instead of requiring username + password.

Added the get_secret and list_secrets methods

---

lib/azure/armrest/virtual_machine_service.rb
spec/fixtures/operations_response.json
spec/virtual_machine_service_spec.rb

Currently VM power operations return nil. This PR modifies them to return a `ResponseHeaders` object. This is more useful in that it let's users check for potential errors, as well as use the response in conjunction with our `wait` and `poll` methods.

Make VM power operations return a ResponseHeader

---

lib/azure/armrest/virtual_machine_service.rb
spec/virtual_machine_service_spec.rb

This PR adds the `list_by_location` method to the VirtualMachineService model.
Normally the Azure REST API does not allow you to filter by location. They did add a separate method that filters by location, but it only seems to apply to VM's. It's not (yet) a general method for all resources.
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listbylocation
This could help in the Azure provider repo where we currently have to pull all VM's and then filter after the fact.

Add list_by_location to VirtualMachineService

---

.travis.yml

This removes Ruby 2.2.x from the test matrix and adds Ruby 2.5.x instead.

Remove Ruby 2.2.x, add Ruby 2.5.x.

---

lib/azure/armrest/resource_provider_service.rb

Let's memoize the `ResourceProviderService#supported?` since that value is unlikely to change.

Memoize the ResourceProviderService#supported? method

---

lib/azure/armrest/configuration.rb
spec/configuration_spec.rb

At the moment the `Azure::Armrest::Configuration.log=` method will bomb if you try to set it to something that's neither a string nor a Logger instance.
For example, if you try to assign it to a `Syslogger` instance you will get a `no implicit conversion of Syslogger into String` error because it tries to pass it to `Logger.new`.
This PR just flips the logic so that only Strings are treated specially, everything else is passed directly.

Update log setter

---

.travis.yml

The travis.yml file is a bit behind the times. This PR updates it to cover 2.5.7 and 2.6.5.

Update travis to just 2.5 and 2.6

---

azure-armrest.gemspec

Update to the latest rest-client version. Sets the stage for us to use per-request logging instead of using a global logger.
See https://github.com/ManageIQ/azure-armrest/issues/389
Note that the current logging will still work with this update.

Update rest-client to 2.1.0

---

lib/azure/armrest/insights/metrics_service.rb

A while back the Microsoft API for metrics collection changed. It used to be that everything had to be done through a `filter` parameter. However, that has changed, and their REST API now accepts several other URI parameters.
https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list#resulttype
The current code, while technically still functional, is no longer particularly useful. This is because in many cases the old filters will no longer work, and will typically be rejected outright. For example, a query that was once written like this will no longer work:
```
filter = "(name.value eq 'Percentage CPU' or name.value eq 'Disk Read Bytes') "
filter << "and startTime eq 2020-02-23 and endTime eq 2020-02-24"
metrics = mets.list_metrics(vm, filter)
```
Using the new API, it would be …

Update the list_metrics method to use the updated API

---

azure-armrest.gemspec

This PR bumps the azure-signature dependency to 0.3.0. The main changes are a dependency change to include activesupport so that it could take advantage of some of that libraries helper methods.
In addition, this version properly includes a LICENSE file as required by the Apache-2.0 license.

Update azure-signature to 0.3.0

---

azure-armrest.gemspec

This will create greater flexibility with the rest-client gem where we're currently experiencing some upgrade pains with ManageIQ. Since the changes in rest-client don't affect this branch, we can loosen the restrictions a bit.

Loosen rest-client dependency on the 0.9.x branch

---

lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/virtual_machine_service.rb

As of June 2018 the Azure REST API was modified to allow inline expansion of the instance view properties in a standard GET call for a single instance:
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get
This would be handy for the Azure provider, since we currently end up making a separate call for each VM to get power state information.
Supporting the `$expand` url parameter was also necessary for this to work.
Oddly, the ability to use `$expand` does not yet appear to be supported for other calls.
Note that this is technically a breaking change and we should consider a major version bump if accepted.

Modify the VirtualMachineService#get method to include instance view information

---

lib/azure/armrest/configuration.rb
spec/spec_helper.rb

Set the default `ssl_version` config option to TLS 1.2 as per the recommendations from Microsoft: https://azure.microsoft.com/en-us/updates/azuretls12/

Update default ssl_version to TLSv1_2

---

.travis.yml

per https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration: `If you currently specify sudo: false in your .travis.yml, we recommend removing that configuration soon...`

cleanup travis.yml

---

lib/azure/armrest/armrest_service.rb

There is no `configuration.resource_url` method. It's supposed to be `configuration.environment.resource_url`.

Fix tenants method

---

azure-armrest.gemspec
lib/azure/armrest.rb
lib/azure/armrest/model/storage_account.rb
lib/azure/armrest/resource_group_based_service.rb
lib/azure/armrest/resource_provider_service.rb
lib/azure/armrest/storage/managed_storage_helper.rb
lib/azure/armrest/virtual_machine_service.rb
spec/configuration_spec.rb

Running the rubocop linter over the code base revealed a bug in the `StorageAccount` model where the `transform_keys` method wasn't actually doing anything. I don't think this showed up because typically the defaults are used.
Additionally, a duplicate exception was corrected, and `options` are now actually passed to the `vm_operate` method, which could potentially affect the `capture` method.
Lastly, a redundant require statement and some useless assignments were removed.

Internal StorageAccount model fixes, other fixes

---

.travis.yml
azure-armrest.gemspec

~~otherwise i think local rubocop will break:~~
```
Bundler could not find compatible versions for gem "simplecov":
In Gemfile:
simplecov
codeclimate-test-reporter (~> 1.0.0) was resolved to 1.0.9, which depends on
simplecov (<= 0.13)
```
which is moot if we remove the dependency anyway, thanks @djberg96

remove test reporter dependency

---

lib/azure/armrest/armrest_service.rb

Fix for:
```
NoMethodError:
undefined method `delegate' for Azure::Armrest::ArmrestService:Class
Did you mean?  deprecate
./lib/azure/armrest/armrest_service.rb:63:in `<class:ArmrestService>'
```

Fix undefine method delegate
